// GENERATED from koi.ts (drawFish, verbatim, long lines cut at 78 chars): the code the launch
// film shows streaming beside the koi as it draws. Regenerate if drawFish changes.
export const KOI_CODE: string[] = [
"export const drawFish = (g: Gfx, k: KoiClock, b: Body, fins: ReturnType<typeo…",
"  // the fish's shadow on the pond floor, flat and hard, down-right away from…",
"  const floor = [b.outline, cau.shape, ...fins.map((f) => f.shape)].map((s) =…",
"  g.group(\"plain\", () => lay(g, k(\"floor\", \"shade\"), floor, () => floor.forEa…",
"",
"  // fins under the body: translucent, cel-shaded, a black base on the pector…",
"  g.group(\"plain\", () => {",
"    fins.forEach((f, i) => {",
"      const el = `fin${i}`, fl = k(el, \"flat\"), sh = k(el, \"shade\"), dt = k(e…",
"      const moto = () => { if (i < 2) fillShape(g, blob(...(i === 0 ? b.at(0.…",
"      const cel = () => { fillShape(g, f.shape, FIN_S, 0.88); clipped(g, f.sh…",
"      if (sh >= 1) cel();",
"      else { lay(g, part(fl, 0, 2), [f.shape], () => fillShape(g, f.shape, FI…",
"      f.rays.forEach((ray, kk) => inkP(g, ray, mix(INK, FIN_S, 0.35), { w: 1.…",
"      inkP(g, f.shape, INK, { w: 4.2, closed: true, light: LIGHT, shadow: 0.8…",
"    });",
"  });",
"",
"  // the body: shade cel underneath, the lit white pushed toward the light, t…",
"  const bs = b.outline, bsL = bs.map(([x, y]) => [x + LIGHT[0] * 22, y + LIGH…",
"  const bfl = k(\"body\", \"flat\"), bsh = k(\"body\", \"shade\");",
"  g.group(\"plain\", () => {",
"    if (bsh >= 1) fillShape(g, bs, WHITE_S);",
"    else { lay(g, bfl, [bs], () => fillShape(g, bs, WHITE), 5201, 34, -0.35);…",
"    clipped(g, bs, () => {",
"      if (bsh >= 1) fillShape(g, bsL, WHITE);",
"      // red hi: head crown, a saddle across the back, a patch toward the tai…",
"      const hf = k(\"hi\", \"flat\"), hs = k(\"hi\", \"shade\");",
"      const patches = KOI_HI;",
"      patches.forEach(([t, s, dt, ds, seed], pi) => {",
"        const r = rng(seed * 17), pts: P[] = [];",
"        for (let i = 0; i < 16; i++) { const a = (i / 16) * Math.PI * 2, kk =…",
"        const sh = smooth(pts, true, 6), ps = part(hs, pi, 5);",
"        const cel = () => { fillShape(g, sh, HI_S); clipped(g, sh, () => fill…",
"        if (ps >= 1) cel(); else { lay(g, part(hf, pi, 5), [sh], () => fillSh…",
"      });",
"      // sumi: a few black spots, never on the head",
"      const sf = k(\"sumi\", \"flat\");",
"      ([[0.3, 0.55, 0.028, 0.32, 31], [0.55, -0.55, 0.03, 0.3, 32], [0.61, 0.…",
"        const r = rng(seed), pts: P[] = []; for (let i = 0; i < 12; i++) { co…",
"        const sp = smooth(pts, true, 5); lay(g, part(sf, si, 5), [sp], () => …",
"      });",
"      // scales: a loose lattice of arcs, strongest on the lit back, gone int…",
"      const r = rng(55), sc = k(\"scales\", \"detail\");",
"      for (let t = 0.2; t < 0.93; t += 0.034) for (let s = -0.75; s <= 0.8; s…",
"        const tt = t + (Math.round(s / 0.3) % 2 ? 0.017 : 0), ss = s + (r() -…",
"        const lit = ss < 0.35 && !(r() < 0.3);",
"        if (lit) inkP(g, smooth([q, m, u], false, 5), \"#2a1f3a\", { w: 1.5, sh…",
"        void p;",
"      }",
"      // the wet highlight along the back, and a glint on the head",
"      const hl = k(\"gloss\", \"detail\");",
"      [[0.2, 0.3, -0.6, 7], [0.335, 0.42, -0.64, 6], [0.46, 0.5, -0.66, 4.5],…",
"      const glint = blob(...b.at(0.075, -0.35), 22, 9, 91, 0.1, 10, -0.7);",
"      lay(g, part(hl, 4, 5), [glint], () => fillShape(g, blob(...b.at(0.075, …",
"    });",
"    // dorsal fin down the spine: a narrow flutter of translucent fin with ra…",
"    const df: P[] = [], dfr: P[] = [];",
"    for (let i = 0; i <= 16; i++) { const f = i / 16, t = 0.36 + f * 0.3, h =…",
"    const dorsal = [...smooth(df, false, 3), ...smooth(dfr, false, 3).reverse…"
];
