"""Multimodal generation tools (OpenRouter backend).

OpenRouter exposes chat-routed generation through the OpenAI-compatible
chat-completions API with extra *output modalities*; speech and the chat-routed
image models POST to ``{base}/chat/completions`` with a ``modalities`` array
and read the generated bytes back from the assistant message:

- ``image_generate``  → ``modalities:["image","text"]`` → ``message.images[].image_url.url``
  (a ``data:image/...;base64,...`` URI). Default model ``openai/gpt-image-2.5-sunburst``
  with provider-default quality. Dedicated image models
  (``gpt-image-*``) are served only by the Images API and answer 404 on
  chat/completions however the modalities are spelled, so they go to
  ``POST {base}/images`` on OpenRouter (``input_references`` carries the edit
  inputs) and to ``/images/generations`` / ``/images/edits`` on an
  OpenAI-compatible base -- by name, and as the fallback when chat/completions
  refuses a model as image-only.
- ``text_to_speech``  → ``modalities:["audio","text"]`` + ``audio:{voice,format}``.
  OpenRouter only returns audio when ``stream:true`` AND only as raw ``pcm16``
  in that mode, so we stream, concatenate the base64 ``delta.audio.data`` chunks,
  and wrap the PCM (24 kHz / mono / 16-bit) into a WAV with the stdlib ``wave``
  module — zero binary dependency. mp3/opus/flac are transcoded from that WAV
  only when ``ffmpeg`` is on PATH; otherwise we keep the WAV and say so.
  Default model ``openai/gpt-audio-mini``.

Video uses a separate async endpoint (NOT chat-completions):

- ``video_generate``  → ``POST {base}/videos`` with ``{model, prompt}`` → ``202``
  ``{id, polling_url, status}`` → poll ``polling_url`` until ``completed`` (URLs
  to download) or ``failed`` (with ``error``). Default model
  ``kwaivgi/kling-v3.0-std`` (Kling v3 Standard). Requires postpaid billing /
  credits enabled on the OpenRouter account.

Generated files are written under ``<working directory>/<output_subdir>`` --
``workdir.current()`` when a turn is bound, the constructor's root otherwise --
and the path is returned so the agent can forward it with the ``message``
tool's ``media`` field. A denied request (HTTP 403) hints at setting ``tools.media.proxy``.

See demos/skill_retrieval/skills/image-gen/SKILL.md for the image recipe.
"""

from __future__ import annotations

import asyncio
import base64
import json
import os
import re
import shutil
import uuid
import wave
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx
from loguru import logger

from raven.agent import workdir
from raven.contracts.token_strategy import UsageSnapshot
from raven.contracts.tool import Tool
from raven.providers.usage import image_usage
from raven.providers.wire import wire_model
from raven.security.network import guarded_fetch
from raven.utils.images import ImagePart, image_block

if TYPE_CHECKING:
    from raven.config.schema import MediaToolConfig

_DEFAULT_BASE = "https://openrouter.ai/api/v1"

_EXT_MIME = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".bmp": "image/bmp",
    ".svg": "image/svg+xml",
}

_MIME_EXT = {mime: ext.lstrip(".") for ext, mime in _EXT_MIME.items()}
_MIME_EXT["image/jpeg"] = "jpg"


class _OpenRouterMediaTool(Tool):
    """Shared base: config/env resolution, chat-completions call, file output."""

    default_model = ""

    def __init__(
        self,
        config: "MediaToolConfig | Callable[[], MediaToolConfig | None] | None" = None,
        *,
        workspace: Path | None = None,
        proxy: str | None = None,
        output_subdir: str = "generated",
        restrict_to_workspace: bool = False,
        usage_recorder: Callable[[UsageSnapshot], Awaitable[None]] | None = None,
    ):
        # A callable is the live form: the loop passes a reader over the config
        # file so a key added or rotated there serves the next call without a
        # re-registration. A plain section (tests, one-shot embedders) stays a
        # snapshot, which for them is also the current file.
        self._config_source = config if callable(config) else None
        self._config_static = None if callable(config) else config
        self._workspace = Path(workspace) if workspace else Path.cwd()
        self._proxy = proxy
        self._output_subdir = output_subdir
        self._restrict_to_workspace = restrict_to_workspace
        self._usage_recorder = usage_recorder

    @property
    def _config(self) -> "MediaToolConfig | None":
        config = self._config_source() if self._config_source is not None else self._config_static
        from raven.config.live import resolve_media_selection

        return resolve_media_selection(config)

    # ── config resolution (at call time, so env/config edits are picked up) ──

    @staticmethod
    def _resolve_key(config: "MediaToolConfig | None") -> str:
        """The credential chain in one place: this tool's section, then the
        shared environment variable.

        A static method so :meth:`has_key` can ask it without an instance --
        this base is abstract, and the callers deciding whether a capability
        works hold a config and no tool.
        """
        cfg_key = getattr(config, "api_key", "") if config else ""
        return cfg_key or os.environ.get("OPENROUTER_API_KEY", "")

    @property
    def api_key(self) -> str:
        return self._resolve_key(self._config)

    @classmethod
    def is_configured(cls, config: "MediaToolConfig | None") -> bool:
        """Whether this deployment asked for the tool at all.

        A model *or* a key, matching what ``AgentLoop`` registers on: the key
        alone would let an OpenRouter credential set for chat quietly switch on
        three tools that bill per call, and the model alone would miss the
        deployment that names no model and relies on ``default_model``.

        A classmethod because the caller deciding whether to offer the tool has
        a config and no instance, and because the answer has to be askable
        without building one.
        """
        if config is None:
            return False
        return bool(config.api_key or config.model)

    def configured(self) -> bool:
        """Whether this tool's section asks for it right now, read live.

        The withheld axis asks this of a tool that declares it (see
        ``raven/contracts/plugin_surface.py``); the answer is :meth:`is_configured`
        on the section the next call would read, so a plugin riding this tool
        is offered and withdrawn on exactly the terms the built-in is.
        """
        return self.is_configured(self._config)

    @classmethod
    def has_key(cls, config: "MediaToolConfig | None") -> bool:
        """Whether a credential resolves for this tool.

        A different question from :meth:`is_configured`, which answers whether
        the deployment asked for the tool at all: a section naming only a model
        is registered and offered to the model, and then every call returns
        :meth:`_no_key_error`. Asked of the tool because only the tool consults
        both the section and ``OPENROUTER_API_KEY``, so a caller reading the
        config alone answers wrong for every deployment that exports it.
        """
        return bool(cls._resolve_key(config))

    @property
    def api_base(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        return (cfg_base or _DEFAULT_BASE).rstrip("/")

    def _model(self, override: str | None) -> str:
        cfg_model = getattr(self._config, "model", "") if self._config else ""
        return override or cfg_model or self.default_model

    def _output_path(self, ext: str, output_dir: str | None = None, stem: str | None = None) -> Path:
        base = workdir.current() or self._workspace
        out_dir = (base / Path(output_dir).expanduser()).resolve() if output_dir else base / self._output_subdir
        if output_dir and self._restrict_to_workspace:
            # The bound session directory may live outside agent home (a
            # launch-dir policy or an explicit override); a confined turn must
            # still be able to keep its images inside its own session.
            roots = {base.resolve(), self._workspace.resolve()}
            if not any(out_dir == root or root in out_dir.parents for root in roots):
                raise PermissionError(f"output_dir {output_dir} is outside the workspace")
        out_dir.mkdir(parents=True, exist_ok=True)
        if not stem:
            return out_dir / f"{self.name}-{uuid.uuid4().hex[:12]}.{ext}"
        return _claim(out_dir, stem, ext)

    def _no_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    f"{self.name}: no API key configured. Set it in "
                    f"~/.raven/config.json under tools.media.*.apiKey, "
                    f"providers.openrouter.apiKey, or export OPENROUTER_API_KEY; "
                    f"it takes effect on the next call."
                )
            },
            ensure_ascii=False,
        )

    async def _record_usage(self, payload: dict[str, Any], model: str, protocol: str) -> None:
        if self._usage_recorder is None:
            return
        try:
            await self._usage_recorder(UsageSnapshot(model=model, **image_usage(payload, protocol)))
        except Exception:
            logger.warning("Image usage recording failed")

    async def _chat(self, payload: dict[str, Any]) -> dict[str, Any]:
        """POST to chat/completions and return the assistant message dict.

        Raises ``httpx.HTTPStatusError`` on non-2xx so callers can format it.
        """
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            r = await client.post(
                f"{self.api_base}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
                json=payload,
            )
            r.raise_for_status()
            data = r.json()
        await self._record_usage(data, payload["model"], "chat")
        choice = (data.get("choices") or [{}])[0]
        message = dict(choice.get("message") or {})
        for key in ("finish_reason", "native_finish_reason"):
            if choice.get(key):
                message[key] = choice[key]
        return message

    def _format_http_error(self, e: httpx.HTTPStatusError) -> str:
        # The status, not the body: ``failure_class`` keys the loop's tool-failure
        # streak on this envelope's ``error`` alone, and a vendor body carries a
        # request id, so interpolating it splits one dead endpoint into a class per
        # call and the stop-repeating nudge never fires. The body moves to ``detail``,
        # which keeps it in front of the model and inside ``is_hard_tool_failure``'s
        # transient-marker scan. The same rule governs every envelope below.
        body = e.response.text[:400]
        answer: dict[str, Any] = {"error": f"HTTP {e.response.status_code}", "detail": body}
        if e.response.status_code == 403:
            answer["hint"] = (
                "Request denied (HTTP 403). You can route media calls through a "
                "proxy via tools.media.proxy (or HTTPS_PROXY) and retry."
            )
        logger.error("{} HTTP {}: {}", self.name, e.response.status_code, body)
        return json.dumps(answer, ensure_ascii=False)


_IMAGE_API_MODELS = (
    "gpt-image",
    "seedream",
    "qwen-image",
    "grok-imagine",
    "flux",
    "recraft",
    "mai-image",
    "krea",
    "riverflow",
    "muse-image",
)
# An OpenAI-compatible base takes a size where OpenRouter takes an aspect ratio.
_SIZES = {
    "1:1": "1024x1024",
    "3:2": "1536x1024",
    "2:3": "1024x1536",
    "4:3": "1536x1152",
    "3:4": "1152x1536",
    "16:9": "1536x864",
    "9:16": "864x1536",
    "21:9": "1536x658",
}

# What the OpenAI Images API accepts for the gpt-image family: three frames and
# "auto". The table above is what OpenRouter's unified route and the other
# families take as a shape; sent to a gpt-image deployment behind an
# OpenAI-compatible base, "1536x864" is refused as an invalid size. So a ratio is
# answered with the nearest frame the family has, and the caller crops to the
# shape it asked for (the deck tools fit a picture to its box).
_GPT_IMAGE_LANDSCAPE = "1536x1024"
_GPT_IMAGE_PORTRAIT = "1024x1536"
_GPT_IMAGE_SQUARE = "1024x1024"


def images_api_size(model_id: str, aspect_ratio: str | None) -> str | None:
    """The ``size`` an OpenAI-compatible Images API is asked for, or None to leave it."""
    if not aspect_ratio or aspect_ratio not in _SIZES:
        return None
    if "gpt-image" not in model_id.lower():
        return _SIZES[aspect_ratio]
    width, height = (int(side) for side in _SIZES[aspect_ratio].split("x"))
    if width == height:
        return _GPT_IMAGE_SQUARE
    return _GPT_IMAGE_LANDSCAPE if width > height else _GPT_IMAGE_PORTRAIT


def _image_only_refusal(e: httpx.HTTPStatusError) -> bool:
    """OpenRouter's two spellings of "this model is not a chat model"."""
    body = e.response.text
    return e.response.status_code == 404 and ("chat/completions" in body or "output modalities" in body)


def _split_data_uri(url: str) -> tuple[str, bytes]:
    head, _, encoded = url.partition(",")
    mime = head[len("data:") :].split(";", 1)[0] or "image/png"
    return mime, base64.b64decode(encoded)


# How many of a batch are in flight at once. The deck engine settled on four for the
# same call (plugins-dist/ppt-engine/raven_ppt/tools/generate_image.py): a batch is
# waited on as a whole, so the ceiling only has to keep the slowest picture from
# arriving last, and a wider fan-out at one key buys 429s instead of images.
_BATCH_CONCURRENCY = 4

# Fields a single picture may carry. `model` and `output_dir` are not among them:
# one call speaks to one deployment and writes into one directory.
_PICTURE_FIELDS = ("prompt", "filename", "images", "aspect_ratio", "quality")

_SAFE_NAME = re.compile(r"[^a-zA-Z0-9._-]+")

# How far the numbering walks before a name falls back to a uuid. A batch is eight
# pictures, not thousands; past this the caller is reusing one name for everything
# and a unique suffix serves better than a longer walk.
_NAME_ATTEMPTS = 512


def _safe_stem(value: Any) -> str:
    """A caller-supplied file name reduced to a bare stem, or "" to keep the generated one.

    The name arrives from the model, so a directory in it is dropped rather than
    honoured: `output_dir` is the only thing that decides where a picture lands.
    """
    name = Path(str(value or "")).name
    return _SAFE_NAME.sub("-", Path(name).stem).strip("-._")


def _claim(out_dir: Path, stem: str, ext: str) -> Path:
    """The first free path for `stem`, taken by creating it.

    A generated name carries a uuid and cannot clash, but a caller-supplied one is
    a plain word, and three things want the same word at once: the pictures of a
    batch that share the call's top-level `filename`, the several images one prompt
    can answer with, and whatever the workspace already holds under that name. The
    name is taken with O_EXCL rather than by testing for the file first -- the
    pictures of a batch are written while the rest are still in flight, so a name
    that was free when it was tested is not one that is still free when it is
    written, and nothing the caller did not generate is ever written over.
    """
    for suffix in range(1, _NAME_ATTEMPTS + 1):
        candidate = out_dir / (f"{stem}.{ext}" if suffix == 1 else f"{stem}-{suffix}.{ext}")
        try:
            os.close(os.open(candidate, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o644))
        except FileExistsError:
            continue
        return candidate
    return out_dir / f"{stem}-{uuid.uuid4().hex[:8]}.{ext}"


def _distinct_stems(wanted: list[dict[str, Any]]) -> list[str]:
    """A name per picture that no other picture of the same batch is aiming at.

    `_claim` alone would keep the files apart, but which picture ends up at the
    bare name would then follow the order the answers happen to come back in. A
    batch that asks twice for the same name says so before anything is in flight,
    so the tie is broken here, by position, and the answer a caller reads is the
    same one every run. A name only one picture asked for is left exactly as it
    was asked for.
    """
    claimed: set[str] = set()
    stems: list[str] = []
    for index, spec in enumerate(wanted):
        asked = _safe_stem(spec.get("filename"))
        stem, bump = asked, index
        while stem and stem in claimed:
            stem = f"{asked}-{bump + 1}"
            bump += 1
        if stem:
            claimed.add(stem)
        stems.append(stem)
    return stems


def _picture_spec(item: Any) -> dict[str, Any]:
    """One item of `prompts` as a spec, with its unset fields left out.

    Left out rather than carried as None, so the call's top-level value stands for
    whatever the item does not name.
    """
    if not isinstance(item, dict):
        return {}
    return {key: value for key, value in item.items() if key in _PICTURE_FIELDS and value is not None}


class ImageGenerateTool(_OpenRouterMediaTool):
    """Generate (or edit) an image from a text prompt via OpenRouter or an OpenAI-compatible Images API."""

    name = "image_generate"
    default_model = "openai/gpt-image-2.5-sunburst"
    description = (
        "Generate images from text prompts (optionally editing/varying input images). "
        "Several pictures in one call, generated at the same time: plan every picture "
        "the task needs, then ask for them together in `prompts` instead of one call "
        "each -- a call is a minute of waiting whether it carries one prompt or eight. "
        "Saves each image under the workspace and returns its file path; forward them "
        "to the user with the `message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the image to create"},
            "model": {
                "type": "string",
                "description": (
                    "Image model used only when Settings has no model, e.g. 'openai/gpt-image-2.5-sunburst'"
                ),
            },
            "images": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Optional input images to edit/vary: local file paths, http(s) URLs, or data: URIs "
                    "(max 6 for chat-routed models, 16 for gpt-image models)"
                ),
            },
            "aspect_ratio": {
                "type": "string",
                "enum": list(_SIZES),
                "description": "Output aspect ratio for gpt-image, seedream, qwen-image and grok-imagine models",
            },
            "quality": {
                "type": "string",
                "enum": ["low", "medium", "high"],
                "description": "Quality used only when Settings has no quality; applies to gpt-image models only",
            },
            "output_dir": {
                "type": "string",
                "description": (
                    "Directory to save into, absolute or relative to the working directory "
                    "(created if missing); defaults to generated/ under the working directory"
                ),
            },
            "filename": {
                "type": "string",
                "description": (
                    "Optional file name for the image, without a directory; a generated "
                    "unique name is used when it is left out. A name already taken -- by "
                    "another picture of the same call, or by a file already there -- is "
                    "numbered rather than written over, so give each picture its own name "
                    "if you want to know which is which"
                ),
            },
            "prompts": {
                "type": "array",
                "description": (
                    "Several images in one call, generated at the same time: plan every picture "
                    "you need, then ask for them together instead of one call each. Each item "
                    "takes its own `prompt` and may override `filename`, `images`, `aspect_ratio` "
                    "and `quality`; whatever an item leaves out falls back to this call's "
                    "top-level value. A top-level `prompt` given alongside is generated as the "
                    "first picture of the batch. `model` and `output_dir` stay shared by the "
                    "whole call. One picture failing does not fail the rest: the answer says per "
                    "picture what was made and why the others were not"
                ),
                "items": {
                    "type": "object",
                    "properties": {
                        "prompt": {"type": "string", "description": "Text description of this image"},
                        "filename": {
                            "type": "string",
                            "description": (
                                "File name for this image, without a directory; a name another "
                                "picture already took is numbered rather than written over"
                            ),
                        },
                        "images": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "Input images to edit/vary for this picture only",
                        },
                        "aspect_ratio": {"type": "string", "enum": list(_SIZES)},
                        "quality": {"type": "string", "enum": ["low", "medium", "high"]},
                    },
                    "required": ["prompt"],
                },
            },
        },
    }

    def _image_part(self, ref: str) -> ImagePart:
        """Build an OpenAI-style image_url content part from a path/URL/data URI."""
        if ref.startswith(("http://", "https://", "data:")):
            return image_block(ref)
        path = Path(ref).expanduser()
        if self._restrict_to_workspace:
            resolved = path.resolve()
            root = self._workspace.resolve()
            if resolved != root and root not in resolved.parents:
                raise PermissionError(f"{ref} is outside the workspace")
        data = path.read_bytes()
        mime = _EXT_MIME.get(path.suffix.lower(), "image/png")
        b64 = base64.b64encode(data).decode("ascii")
        return image_block(f"data:{mime};base64,{b64}")

    def effective_quality(self, requested: str | None, model_id: str | None = None) -> str | None:
        """The quality a call sends: Settings' where it names one, else the request's.

        ``medium`` when neither says and the model is gpt-image-2, and ``None`` for a
        family without the knob (only gpt-image takes one). Public because a caller
        that caches on what it asked for has to key on what was actually sent: the
        deck's generator keyed on its own default while the host sent Settings' value,
        so a quality changed in Settings was answered from the old cache.
        """
        config = self._config
        model_id = model_id or self._model(None)
        if "quality" in getattr(config, "model_fields_set", set()):
            quality = config.quality
        elif requested is None:
            quality = "medium" if model_id.rsplit("/", 1)[-1].lower() == "gpt-image-2" else None
        else:
            quality = requested
        return quality if "gpt-image" in model_id.lower() else None

    async def execute(
        self,
        prompt: str = "",
        model: str | None = None,
        images: list[str] | None = None,
        aspect_ratio: str | None = None,
        quality: str | None = None,
        output_dir: str | None = None,
        filename: str | None = None,
        prompts: list[dict[str, Any]] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()
        shared = {
            key: value
            for key, value in (
                ("images", images),
                ("aspect_ratio", aspect_ratio),
                ("quality", quality),
                ("filename", filename),
            )
            if value is not None
        }
        wanted = [{**shared, **_picture_spec(item)} for item in (prompts or [])]
        if str(prompt or "").strip():
            wanted.insert(0, {**shared, "prompt": prompt})
        if not wanted:
            return json.dumps(
                {"error": 'nothing to generate: give prompt, or prompts=[{"prompt": ...}, ...]'},
                ensure_ascii=False,
            )
        blank = next((i for i, spec in enumerate(wanted) if not str(spec.get("prompt") or "").strip()), None)
        if blank is not None:
            return json.dumps({"error": "a picture has no prompt", "index": blank}, ensure_ascii=False)
        if len(wanted) == 1:
            return await self._generate_one(wanted[0], _safe_stem(wanted[0].get("filename")), model, output_dir)
        stems = _distinct_stems(wanted)
        gate = asyncio.Semaphore(_BATCH_CONCURRENCY)

        async def one(spec: dict[str, Any], stem: str) -> str:
            async with gate:
                return await self._generate_one(spec, stem, model, output_dir)

        # Gathered with the exceptions, not through them: a directory refused for one
        # picture, or a reference it cannot read, is that picture's answer -- the seven
        # the caller waited for alongside it still come back.
        answers = await asyncio.gather(*(one(spec, stem) for spec, stem in zip(wanted, stems)), return_exceptions=True)
        return self._batch_answer(wanted, answers)

    def _batch_answer(self, wanted: list[dict[str, Any]], answers: list[str | BaseException]) -> str:
        """Fold the per-picture answers into one, keeping every path under `paths`.

        A picture that failed takes its reason with it instead of the batch: the
        caller asks again for those and forwards the rest, which is the whole point
        of asking for eight at once.
        """
        results: list[dict[str, Any]] = []
        paths: list[str] = []
        for index, (spec, answer) in enumerate(zip(wanted, answers)):
            if isinstance(answer, BaseException):
                logger.error("image_generate: picture {} failed: {}", index, answer)
                reply: dict[str, Any] = {"error": f"{type(answer).__name__}: {answer}"}
            else:
                try:
                    reply = json.loads(answer)
                except (TypeError, ValueError):
                    reply = {"error": f"no usable answer: {answer!r}"}
            item: dict[str, Any] = {"index": index, "prompt": str(spec.get("prompt") or "")[:120]}
            if reply.get("paths"):
                item["paths"] = reply["paths"]
                paths.extend(reply["paths"])
            else:
                item["error"] = reply.get("error") or "no image returned"
                # Every key ``error`` was split into travels with it: the reason a
                # picture failed, the proxy a 403 can be routed through, the
                # reference that was refused. ``error`` carries only the class now,
                # so a key left behind here is a batched picture told strictly less
                # than the single call is.
                for key in ("detail", "hint", "url", "note", "finish_reason", "retryable"):
                    if reply.get(key) is not None:
                        item[key] = reply[key]
            if reply.get("model"):
                item["model"] = reply["model"]
            results.append(item)
        failed = [item for item in results if item.get("error")]
        answer_body: dict[str, Any] = {
            "success": bool(paths),
            "model": next((item["model"] for item in results if item.get("model")), self._model(None)),
            "paths": paths,
            "results": results,
        }
        if failed:
            answer_body["failed"] = len(failed)
            answer_body["note"] = (
                f"{len(failed)} of {len(results)} images failed; the reason is on each result. "
                "Ask again only for those, in one call."
            )
        logger.info("image_generate: {} of {} image(s) made in one call", len(paths), len(results))
        return json.dumps(answer_body, ensure_ascii=False)

    async def _generate_one(self, spec: dict[str, Any], stem: str, model: str | None, output_dir: str | None) -> str:
        prompt = str(spec.get("prompt") or "")
        images = list(spec.get("images") or []) or None
        aspect_ratio = spec.get("aspect_ratio") or None
        config = self._config
        model_id = getattr(config, "model", "") or model or self.default_model
        if httpx.URL(self.api_base).host == "openrouter.ai":
            model_id = wire_model(model_id, client_provider="openrouter")
        quality = self.effective_quality(spec.get("quality"), model_id)
        # The Images API takes the frame only from the families known to honour
        # it; the chat route takes it from any model, as image_config below.
        frames = any(name in model_id.lower() for name in ("gpt-image", "seedream", "qwen-image", "grok-imagine"))
        if any(name in model_id.lower() for name in _IMAGE_API_MODELS):
            return await self._via_images_api(
                model_id, prompt, images, aspect_ratio if frames else None, quality, output_dir, stem
            )
        if images:
            content: Any = [{"type": "text", "text": prompt}]
            try:
                for ref in images[:6]:
                    content.append(self._image_part(ref))
            except OSError as e:
                return json.dumps({"error": "could not read input image", "detail": str(e)}, ensure_ascii=False)
        else:
            content = prompt

        payload: dict[str, Any] = {
            "model": model_id,
            "messages": [{"role": "user", "content": content}],
            "modalities": ["image", "text"],
        }
        # The chat route's frame knob (OpenRouter's image_config); a chat-routed
        # model given nothing answers in its own default frame whatever was asked.
        if aspect_ratio:
            payload["image_config"] = {"aspect_ratio": aspect_ratio}

        try:
            msg = await self._chat(payload)
        except httpx.HTTPStatusError as e:
            if _image_only_refusal(e):
                return await self._via_images_api(
                    model_id, prompt, images, aspect_ratio if frames else None, quality, output_dir, stem
                )
            return self._format_http_error(e)
        except Exception as e:
            logger.error("image_generate error: {}", e)
            return json.dumps({"error": type(e).__name__, "detail": str(e)}, ensure_ascii=False)

        out_images = msg.get("images") or []
        if not out_images:
            note = msg.get("content") or msg.get("refusal") or ""
            return json.dumps(
                {
                    "error": "image generation refused"
                    if msg.get("finish_reason") == "content_filter"
                    else "no image returned",
                    "model": model_id,
                    "note": note[:300],
                    "finish_reason": msg.get("finish_reason"),
                    "native_finish_reason": msg.get("native_finish_reason"),
                    "retryable": msg.get("finish_reason") != "content_filter",
                },
                ensure_ascii=False,
            )

        paths: list[str] = []
        for item in out_images:
            url = (item.get("image_url") or {}).get("url", "")
            if not url.startswith("data:"):
                continue
            mime, data = _split_data_uri(url)
            path = self._output_path(_MIME_EXT.get(mime, "png"), output_dir, stem)
            path.write_bytes(data)
            paths.append(str(path))

        if not paths:
            return json.dumps({"error": "image payload was not a data URI", "model": model_id}, ensure_ascii=False)

        logger.info("image_generate: {} image(s) via {} -> {}", len(paths), model_id, paths)
        return json.dumps(
            {"success": True, "model": model_id, "quality": quality or "", "paths": paths}, ensure_ascii=False
        )

    async def _via_images_api(
        self,
        model_id: str,
        prompt: str,
        images: list[str] | None,
        aspect_ratio: str | None,
        quality: str | None,
        output_dir: str | None = None,
        stem: str = "",
    ) -> str:
        """The Images API: OpenRouter's unified ``/images``, or ``/images/generations``
        and ``/images/edits`` on an OpenAI-compatible base."""
        headers = {"Authorization": f"Bearer {self.api_key}"}
        openrouter = httpx.URL(self.api_base).host == "openrouter.ai"
        try:
            # OpenRouter takes the chat content-part shape verbatim; the OpenAI
            # edits form takes the bytes behind it.
            refs = [self._image_part(ref) for ref in (images or [])[:16]]
        except OSError as e:
            return json.dumps({"error": "could not read input image", "detail": str(e)}, ensure_ascii=False)
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=300.0) as client:
                if openrouter:
                    body: dict[str, Any] = {"model": model_id, "prompt": prompt, "n": 1}
                    if aspect_ratio:
                        body["aspect_ratio"] = aspect_ratio
                    if quality:
                        body["quality"] = quality
                    if refs:
                        body["input_references"] = refs
                    r = await client.post(f"{self.api_base}/images", headers=headers, json=body)
                elif refs:
                    files = []
                    for i, part in enumerate(refs):
                        url = part["image_url"]["url"]
                        if url.startswith("data:"):
                            mime, data = _split_data_uri(url)
                        else:
                            # A model-supplied URL, so the target is judged before
                            # every hop: read unguarded, a reference pointing inward
                            # would have this process fetch it and upload the bytes.
                            fetched = await guarded_fetch(client, url, what="image reference")
                            if fetched is None:
                                return json.dumps(
                                    {"error": "input image refused: not a fetchable public target", "url": url},
                                    ensure_ascii=False,
                                )
                            fetched.raise_for_status()
                            mime, data = fetched.headers.get("content-type", "image/png"), fetched.content
                        files.append(("image[]", (f"ref{i}.{mime.rsplit('/', 1)[-1]}", data, mime)))
                    form = {"model": model_id, "prompt": prompt, "n": "1"}
                    if size := images_api_size(model_id, aspect_ratio):
                        form["size"] = size
                    if quality:
                        form["quality"] = quality
                    r = await client.post(f"{self.api_base}/images/edits", headers=headers, data=form, files=files)
                else:
                    body = {"model": model_id, "prompt": prompt, "n": 1}
                    if size := images_api_size(model_id, aspect_ratio):
                        body["size"] = size
                    if quality:
                        body["quality"] = quality
                    r = await client.post(f"{self.api_base}/images/generations", headers=headers, json=body)
                r.raise_for_status()
                payload = r.json()
                await self._record_usage(payload, model_id, "images")
                items = payload.get("data") or []
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("image_generate error: {}", e)
            return json.dumps({"error": type(e).__name__, "detail": str(e)}, ensure_ascii=False)
        paths: list[str] = []
        for item in items:
            encoded = item.get("b64_json") if isinstance(item, dict) else None
            if not encoded:
                continue
            path = self._output_path(_MIME_EXT.get(item.get("media_type"), "png"), output_dir, stem)
            path.write_bytes(base64.b64decode(encoded))
            paths.append(str(path))
        if not paths:
            return json.dumps({"error": "no image returned", "model": model_id}, ensure_ascii=False)
        logger.info("image_generate: {} image(s) via {} (images api) -> {}", len(paths), model_id, paths)
        return json.dumps(
            {"success": True, "model": model_id, "quality": quality or "", "paths": paths}, ensure_ascii=False
        )


class SpeechGenerateTool(_OpenRouterMediaTool):
    """Synthesize speech from text via an OpenRouter audio model (gpt-audio)."""

    name = "text_to_speech"
    default_model = "openai/gpt-audio-mini"
    description = (
        "Synthesize speech audio from text. Saves an audio file under the "
        "workspace and returns its path; forward it with the `message` tool's "
        "`media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "text": {"type": "string", "description": "Text to speak"},
            "voice": {
                "type": "string",
                "description": "Voice name (e.g. alloy, echo, fable, onyx, nova, shimmer)",
                "default": "alloy",
            },
            "format": {
                "type": "string",
                "enum": ["wav", "mp3", "opus", "flac"],
                "default": "wav",
                "description": (
                    "Output container. 'wav' is always available (zero deps); "
                    "mp3/opus/flac require ffmpeg on PATH and fall back to wav if absent."
                ),
            },
            "model": {
                "type": "string",
                "description": "Optional OpenRouter audio model override (e.g. openai/gpt-audio)",
            },
        },
        "required": ["text"],
    }

    # OpenRouter streams audio as raw pcm16; OpenAI's gpt-audio emits it at
    # 24 kHz, mono, 16-bit — the params needed to wrap it into a valid WAV.
    _PCM_RATE = 24_000
    _PCM_CHANNELS = 1
    _PCM_SAMPWIDTH = 2

    async def execute(
        self,
        text: str,
        voice: str = "alloy",
        format: str = "wav",
        model: str | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        payload = {
            "model": model_id,
            # Instruct verbatim narration — gpt-audio is conversational, so an
            # explicit directive keeps it from ad-libbing a reply.
            "messages": [
                {
                    "role": "user",
                    "content": f"Read the following text aloud verbatim, adding nothing:\n\n{text}",
                }
            ],
            "modalities": ["audio", "text"],
            # OpenRouter rejects audio output unless stream=true, and in stream
            # mode only the raw pcm16 format is accepted — we wrap/transcode after.
            "stream": True,
            "audio": {"voice": voice, "format": "pcm16"},
        }

        try:
            pcm, transcript = await self._stream_audio_pcm(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("text_to_speech error: {}", e)
            return json.dumps({"error": type(e).__name__, "detail": str(e)}, ensure_ascii=False)

        if not pcm:
            return json.dumps(
                {"error": "no audio returned", "model": model_id, "note": transcript[:300]},
                ensure_ascii=False,
            )

        wav_path = self._output_path("wav")
        self._write_wav(wav_path, pcm)
        out_path, out_fmt, note = await self._maybe_transcode(wav_path, format)

        logger.info("text_to_speech: via {} -> {}", model_id, out_path)
        result: dict[str, Any] = {
            "success": True,
            "model": model_id,
            "path": str(out_path),
            "format": out_fmt,
        }
        if transcript:
            result["transcript"] = transcript
        if note:
            result["note"] = note
        return json.dumps(result, ensure_ascii=False)

    async def _stream_audio_pcm(self, payload: dict[str, Any]) -> tuple[bytes, str]:
        """Stream a chat-completions audio response → (pcm16 bytes, transcript).

        Concatenates the base64 ``delta.audio.data`` chunks (and any transcript
        text) from the SSE stream. Raises ``httpx.HTTPStatusError`` on non-2xx so
        ``execute`` can format it the same way as the image path.
        """
        pcm = bytearray()
        transcript_parts: list[str] = []
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            async with client.stream("POST", f"{self.api_base}/chat/completions", headers=headers, json=payload) as r:
                if r.status_code >= 400:
                    await r.aread()  # load body so .text/raise_for_status carry the error
                    r.raise_for_status()
                async for line in r.aiter_lines():
                    if not line.startswith("data:"):
                        continue
                    data = line[len("data:") :].strip()
                    if data == "[DONE]":
                        break
                    try:
                        obj = json.loads(data)
                    except json.JSONDecodeError:
                        continue
                    delta = (obj.get("choices") or [{}])[0].get("delta") or {}
                    audio = delta.get("audio") or {}
                    if chunk := audio.get("data"):
                        pcm += base64.b64decode(chunk)
                    if t := audio.get("transcript"):
                        transcript_parts.append(t)
        return bytes(pcm), "".join(transcript_parts)

    def _write_wav(self, path: Path, pcm: bytes) -> None:
        """Wrap raw pcm16 bytes into a WAV container (stdlib, no deps)."""
        with wave.open(str(path), "wb") as w:
            w.setnchannels(self._PCM_CHANNELS)
            w.setsampwidth(self._PCM_SAMPWIDTH)
            w.setframerate(self._PCM_RATE)
            w.writeframes(pcm)

    async def _maybe_transcode(self, wav_path: Path, fmt: str) -> tuple[Path, str, str]:
        """Transcode the WAV to ``fmt`` via ffmpeg. Returns (path, format, note).

        wav needs nothing; other formats need ffmpeg and fall back to wav with a
        note when it is missing or the conversion fails.
        """
        if fmt == "wav":
            return wav_path, "wav", ""
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            return wav_path, "wav", f"ffmpeg not on PATH; saved as wav instead of {fmt}"
        out = wav_path.with_suffix(f".{fmt}")
        proc = await asyncio.create_subprocess_exec(
            ffmpeg,
            "-y",
            "-i",
            str(wav_path),
            str(out),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, err = await proc.communicate()
        if proc.returncode != 0 or not out.exists():
            logger.warning("ffmpeg transcode to {} failed: {}", fmt, err.decode("utf-8", "replace")[:200])
            return wav_path, "wav", f"ffmpeg transcode to {fmt} failed; saved as wav"
        wav_path.unlink(missing_ok=True)
        return out, fmt, ""


def _find_video_url(obj: Any) -> str | None:
    """Recursively find the first downloadable video URL / data URI in a response.

    The exact completed-response shape for OpenRouter's /videos endpoint is not
    publicly pinned down, so we search defensively rather than hard-code a path.
    """
    if isinstance(obj, str):
        s = obj
        if s.startswith("data:video") or (
            s.startswith(("http://", "https://"))
            and any(ext in s.lower() for ext in (".mp4", ".webm", ".mov", "video"))
        ):
            return s
        return None
    if isinstance(obj, dict):
        # Prefer obvious keys first.
        for key in ("url", "video_url", "download_url", "video", "output", "result"):
            if key in obj and (found := _find_video_url(obj[key])):
                return found
        for v in obj.values():
            if found := _find_video_url(v):
                return found
        return None
    if isinstance(obj, list):
        for item in obj:
            if found := _find_video_url(item):
                return found
        return None
    return None


def _pick_video_url(status: dict[str, Any]) -> str | None:
    """Choose the downloadable content URL from a completed /videos response.

    OpenRouter's completed shape exposes the rendered video under
    ``signed_urls`` / ``unsigned_urls`` (lists). We prefer those explicitly:
    the job's own ``polling_url`` also lives under ``/videos/`` and would
    otherwise be matched by ``_find_video_url``'s "video" substring heuristic,
    yielding the status JSON instead of the clip. For any other (undocumented)
    provider shape we fall back to a defensive scan that excludes the
    polling/status URL.
    """
    for key in ("signed_urls", "unsigned_urls"):
        urls = status.get(key)
        if isinstance(urls, list) and urls and isinstance(urls[0], str):
            return urls[0]
    scannable = {k: v for k, v in status.items() if k != "polling_url"}
    return _find_video_url(scannable)


class VideoGenerateTool(_OpenRouterMediaTool):
    """Generate a video from a text prompt via Kling on OpenRouter (async)."""

    name = "video_generate"
    default_model = "kwaivgi/kling-v3.0-std"  # Kling v3 Standard
    description = (
        "Generate a short video from a text prompt (async; takes a while). Saves "
        "the video under the workspace and returns its path; forward it with the "
        "`message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the video"},
            "model": {
                "type": "string",
                "description": "Optional OpenRouter video model override (default kwaivgi/kling-v3.0-std)",
            },
            "params": {
                "type": "object",
                "description": (
                    "Optional extra provider params merged into the request, e.g. "
                    '{"duration": 5, "aspect_ratio": "16:9"} (3-15s; 16:9/9:16/1:1)'
                ),
            },
        },
        "required": ["prompt"],
    }

    _POLL_INTERVAL_S = 6.0
    _POLL_TIMEOUT_S = 600.0
    # Backstop above the 600s polling cap; the poll loop gives up first.
    timeout_seconds = 660.0

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        params: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        body: dict[str, Any] = {"model": model_id, "prompt": prompt}
        if params:
            body.update(params)

        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=120.0) as client:
                # 1) submit job
                r = await client.post(f"{self.api_base}/videos", headers=headers, json=body)
                r.raise_for_status()
                job = r.json()
                poll_url = job.get("polling_url") or f"{self.api_base}/videos/{job.get('id')}"

                # 2) poll
                status = await self._poll(client, poll_url, headers)
                state = status.get("status")
                if state != "completed":
                    return json.dumps(
                        {
                            "error": f"video job status={state}",
                            "detail": status.get("error") or status,
                            "model": model_id,
                        },
                        ensure_ascii=False,
                    )

                # 3) locate + download the video
                video_url = _pick_video_url(status)
                if not video_url:
                    return json.dumps(
                        {"error": "completed but no video URL found", "raw": status},
                        ensure_ascii=False,
                    )
                if video_url.startswith("data:"):
                    data = base64.b64decode(video_url.split(",", 1)[1])
                else:
                    # OpenRouter returns "unsigned" content URLs on its own host
                    # that need the same Authorization header as the API. Only
                    # send it to OpenRouter — never leak the key to a third-party
                    # (pre-signed CDN/S3) host.
                    dl_headers = self._api_headers_for(video_url, headers)
                    dl = await client.get(video_url, headers=dl_headers, timeout=180.0)
                    dl.raise_for_status()
                    data = dl.content
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("video_generate error: {}", e)
            return json.dumps({"error": type(e).__name__, "detail": str(e)}, ensure_ascii=False)

        path = self._output_path("mp4")
        path.write_bytes(data)
        logger.info("video_generate: {} bytes via {} -> {}", len(data), model_id, path)
        return json.dumps({"success": True, "model": model_id, "path": str(path)}, ensure_ascii=False)

    def _is_api_origin(self, url: str) -> bool:
        """Is this URL on the same origin as the configured API base?

        Parsed, not a string prefix. ``url.startswith(self.api_base)`` was
        satisfied by any host that merely began with the base string, so
        ``https://openrouter.ai/api/v1.attacker.example/steal`` passed the test
        and collected the provider key. Scheme, host and port all have to
        match; httpx normalizes a default port to None on both sides.
        """
        try:
            target, base = httpx.URL(url), httpx.URL(self.api_base)
        except Exception:  # noqa: BLE001 - an unparseable URL is not our origin
            return False
        return (target.scheme, target.host, target.port) == (base.scheme, base.host, base.port)

    def _api_headers_for(self, url: str, headers: dict[str, str]) -> dict[str, str] | None:
        """The API headers, but only for the API's own origin.

        Every URL here arrives in a provider response -- the poll target and the
        content URL both -- so "where the response told us to go" decides where
        the key would travel. It travels nowhere but home.
        """
        if self._is_api_origin(url):
            return headers
        logger.warning("media_gen: {} is not the configured API origin; fetching it without credentials", url)
        return None

    async def _poll(self, client: httpx.AsyncClient, poll_url: str, headers: dict[str, str]) -> dict[str, Any]:
        """Poll until the job leaves the pending/processing state or times out."""
        waited = 0.0
        while waited < self._POLL_TIMEOUT_S:
            r = await client.get(poll_url, headers=self._api_headers_for(poll_url, headers))
            r.raise_for_status()
            job = r.json()
            if job.get("status") not in ("pending", "processing", "queued", "in_progress"):
                return job
            await asyncio.sleep(self._POLL_INTERVAL_S)
            waited += self._POLL_INTERVAL_S
        return {"status": "timeout"}
