import React from 'react';
import { AbsoluteFill, Sequence, Audio } from 'remotion';
import { COLORS } from '../../brand';
import { P, CamBeat, PhotoBeat, PipelineBeat, CostBeat, StatementBeat, EndCard } from './ShortAiTest';

// =============================================================================
// COMPOSITION CONFIG
// =============================================================================
// Same 9-beat Short as ShortAiTest, with the on-cam clips generated by
// Creatify Aurora (720p) instead of OmniHuman v1.5 — the A/B variant.
export const compositionConfig = {
  id: 'ShortAiTestAurora',
  durationInSeconds: 39.4,
  fps: 30,
  width: 1080,
  height: 1920,
};

type Beat = { id: string; kind: 'cam' | 'tsx'; dur: number; caption?: string };
const BEATS: Beat[] = [
  { id: 'b1', kind: 'cam', dur: 94, caption: "The person talking to you right now… doesn't exist." },
  { id: 'b2', kind: 'tsx', dur: 98 },
  { id: 'b3', kind: 'cam', dur: 110, caption: 'I never recorded this. Not the video. Not even the voice.' },
  { id: 'b4', kind: 'tsx', dur: 238 },
  { id: 'b5', kind: 'cam', dur: 103, caption: 'An AI is reading this script, with my voice… right now.' },
  { id: 'b6', kind: 'tsx', dur: 141 },
  { id: 'b7', kind: 'cam', dur: 55, caption: "Two dollars. And you can't tell." },
  { id: 'b8', kind: 'tsx', dur: 158 },
  { id: 'b9', kind: 'cam', dur: 109, caption: 'Watch it again… and find the glitch.' },
  { id: 'end', kind: 'tsx', dur: 75 },
];
const FROM: number[] = [];
BEATS.reduce((acc, b, i) => { FROM[i] = acc; return acc + b.dur; }, 0);

// =============================================================================
// MAIN COMPONENT
// =============================================================================
const ShortAiTestAurora: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.d900 }}>
      {BEATS.map((b, i) => (
        <Sequence key={b.id} from={FROM[i]} durationInFrames={b.dur}>
          {b.kind === 'cam' ? (
            <CamBeat src={`cam-aurora/${b.id}.mp4`} caption={b.caption} />
          ) : (
            <>
              {b.id === 'b2' && <PhotoBeat />}
              {b.id === 'b4' && <PipelineBeat />}
              {b.id === 'b6' && <CostBeat />}
              {b.id === 'b8' && <StatementBeat />}
              {b.id === 'end' && <EndCard />}
              {b.id !== 'end' && <Audio src={P(`vo/${b.id}.mp3`)} />}
            </>
          )}
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};

export default ShortAiTestAurora;
