#!/usr/bin/env node
// Raven i18n codegen.
//
// Reads the repo-level `i18n/messages.json` (single source of truth, shared
// with the GUI, which inlines the same file at build time) and emits
// `ui-tui/src/i18n/messages.generated.ts`. Generated rather than imported so
// the TUI keeps `rootDir: src` and ships one self-contained bundle.
//
// Usage:
//   node scripts/gen-i18n.mjs            # write messages.generated.ts
//   node scripts/gen-i18n.mjs --check    # exit 1 when the checked-in file
//                                        # is stale (CI lint mode)

import { readFile, writeFile } from 'node:fs/promises'
import prettier from 'prettier'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const SOURCE = resolve(here, '../../i18n/messages.json')
const TARGET = resolve(here, '../src/i18n/messages.generated.ts')

const header = `// GENERATED by scripts/gen-i18n.mjs from i18n/messages.json -- do not edit.
// Run \`npm run gen:i18n\` after changing the catalogue.

export type Locale = 'en' | 'zh'

export interface SlashText {
  help?: string
  name?: string
}
`

const render = catalogue => {
  const slash = {}
  for (const [id, byLocale] of Object.entries(catalogue.slash ?? {})) {
    for (const [locale, text] of Object.entries(byLocale)) {
      slash[locale] ??= {}
      slash[locale][id] = text
    }
  }

  const ui = {}
  for (const [key, byLocale] of Object.entries(catalogue.ui ?? {})) {
    for (const [locale, text] of Object.entries(byLocale)) {
      ui[locale] ??= {}
      ui[locale][key] = text
    }
  }

  return `${header}
export const SLASH_TEXT: Record<Locale, Record<string, SlashText>> = ${JSON.stringify(slash, null, 2)} as Record<
  Locale,
  Record<string, SlashText>
>

export const UI_TEXT: Record<Locale, Record<string, string>> = ${JSON.stringify(ui, null, 2)} as Record<
  Locale,
  Record<string, string>
>
`
}

const catalogue = JSON.parse(await readFile(SOURCE, 'utf8'))
// Run the render through prettier with the repo's own config: this file is
// checked by both `lint:i18n` (is it stale?) and prettier (is it formatted?),
// and a generator that emits an unformatted shape makes those two gates
// contradict each other -- one demands a change the other then rejects.
const config = (await prettier.resolveConfig(TARGET)) ?? {}
const out = await prettier.format(render(catalogue), { ...config, filepath: TARGET })

if (process.argv.includes('--check')) {
  const current = await readFile(TARGET, 'utf8').catch(() => '')

  if (current !== out) {
    console.error('i18n: src/i18n/messages.generated.ts is stale -- run `npm run gen:i18n`')
    process.exit(1)
  }

  console.log('i18n: generated catalogue is up to date')
} else {
  await writeFile(TARGET, out, 'utf8')
  console.log(`i18n: wrote ${TARGET}`)
}
