// 把 scene 列表 → Remotion JSX 主文件
// 输出:src/_generated.jsx 和 src/_generated_index.jsx

const fs = require('fs');
const path = require('path');

// === 内置模板(fast path)===
const TEMPLATES = {
  Title:       {file: '../templates/Title.jsx',       export: 'Title'},
  ContentCard: {file: '../templates/ContentCard.jsx', export: 'ContentCard'},
  TwoColumn:   {file: '../templates/TwoColumn.jsx',   export: 'TwoColumn'},
  Triangle:    {file: '../templates/Triangle.jsx',    export: 'Triangle'},
  BeforeAfter: {file: '../templates/BeforeAfter.jsx', export: 'BeforeAfter'},
  Outro:       {file: '../templates/Outro.jsx',       export: 'Outro'},
};

// === Custom 模板(flexible path)— 在 custom/ 目录里 ===
function resolveCustomTemplate(name) {
  const customDir = path.resolve(__dirname, 'custom');
  const candidate = path.join(customDir, `${name}.jsx`);
  if (fs.existsSync(candidate)) {
    return {file: `../custom/${name}.jsx`, export: name, isCustom: true};
  }
  return null;
}

function resolveTemplate(name) {
  if (TEMPLATES[name]) return TEMPLATES[name];
  return resolveCustomTemplate(name);
}

function generateComposition({meta, scenes}, outputName = 'GeneratedVideo') {
  const totalFrames = scenes.reduce((sum, s) => sum + s.durationInFrames, 0);

  const usedTemplates = [...new Set(scenes.map(s => s.template))];
  const resolved = {};
  const missing = [];
  for (const t of usedTemplates) {
    const cfg = resolveTemplate(t);
    if (cfg) resolved[t] = cfg;
    else missing.push(t);
  }
  if (missing.length) {
    console.error(`\n❌ 找不到模板: ${missing.join(', ')}`);
    console.error('   请让 agent 在 custom/ 目录里创建对应的 jsx 文件:');
    missing.forEach(m => console.error(`   custom/${m}.jsx`));
    console.error('\n   每个文件需要 export 一个跟文件同名的 React component.');
    console.error('   参考: custom/_TEMPLATE.jsx.example');
    throw new Error('Missing templates');
  }

  const imports = usedTemplates.map(t => {
    const cfg = resolved[t];
    return `import {${cfg.export}} from '${cfg.file}';`;
  }).join('\n');

  let cumFrame = 0;
  const sequences = scenes.map(s => {
    const from = cumFrame;
    cumFrame += s.durationInFrames;
    const propsStr = JSON.stringify(s.props, null, 2)
      .replace(/^/gm, '          ');
    return `      <Sequence from={${from}} durationInFrames={${s.durationInFrames}}>
        <${s.template}
          {...${propsStr.trim()}}
        />
      </Sequence>`;
  }).join('\n');

  const compositionCode = `// AUTO-GENERATED by knowledge-explainer-skill — DO NOT EDIT BY HAND
import React from 'react';
import {Sequence, AbsoluteFill} from 'remotion';
${imports}

export const ${outputName} = () => (
  <AbsoluteFill style={{background: '#0a0a0f'}}>
${sequences}
  </AbsoluteFill>
);
`;

  const indexCode = `// AUTO-GENERATED — DO NOT EDIT
import React from 'react';
import {registerRoot, Composition} from 'remotion';
import {${outputName}} from './_generated';

export const Root = () => (
  <>
    <Composition
      id="${outputName}"
      component={${outputName}}
      durationInFrames={${totalFrames}}
      fps={${meta.fps}}
      width={${meta.width}}
      height={${meta.height}}
    />
  </>
);

registerRoot(Root);
`;

  return {compositionCode, indexCode, totalFrames, validScenes: scenes.length};
}

module.exports = {generateComposition};

if (require.main === module) {
  const {parseScript} = require('./parser');
  const inputPath = process.argv[2];
  if (!inputPath) {
    console.error('用法: node generator.js <script.md>');
    process.exit(1);
  }
  const md = fs.readFileSync(inputPath, 'utf8');
  const parsed = parseScript(md);
  const result = generateComposition(parsed);
  console.log(result.compositionCode);
}
