"""Real requests through the provider stack, because mocks cannot see this layer.

Every ``acompletion`` in the unit suite is mocked and the wire-format baseline is
generated by the code it checks, so "the id we send is right" is a closed loop:
it asserts the string equals the string that was recorded. A green unit suite
therefore says nothing about the wire, which is what this file is for.

So this file sends. It is opt-in: without a key every test skips, and it is not
part of the default run (``tests/integration`` is excluded from ``uv run pytest``
by ``norecursedirs``). Run it deliberately::

    OPENROUTER_API_KEY=... uv run pytest tests/integration/test_provider_real_llm.py -v

What it covers is the matrix the mocked tests structurally cannot:

* the gateway routing shapes -- a prefixed id through the gateway, and a bare
  id resolved by the pin;
* the cache-breakpoint rule, as the token counts the vendor actually billed;
* the learned downgrade for an upstream that refuses the field;
* the credential probe, against a live endpoint rather than a mock transport.

Costs a handful of cheap completions per run, capped at 16 output tokens each.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from raven.contracts.llm_provider import GenerationSettings
from raven.providers.litellm_provider import LiteLLMProvider

pytestmark = pytest.mark.asyncio


def _config_key(provider: str) -> str:
    """A key from the user's own config, so a configured machine needs no env."""
    path = Path.home() / ".raven" / "config.json"
    try:
        section = json.loads(path.read_text(encoding="utf-8")).get("providers", {}).get(provider) or {}
    except Exception:
        return ""
    return section.get("apiKey") or section.get("api_key") or ""


OPENROUTER_KEY = os.environ.get("OPENROUTER_API_KEY") or _config_key("openrouter")

requires_openrouter = pytest.mark.skipif(not OPENROUTER_KEY, reason="no OpenRouter credential (env or ~/.raven)")

#: Long enough to clear every vendor's minimum cacheable prefix.
FILLER = "You are a meticulous release engineer. Track every constraint stated below and never restate it. " * 420

ANTHROPIC_MODEL = "openrouter/anthropic/claude-fable-5"
NON_ANTHROPIC_MODEL = "openrouter/google/gemini-3.5-flash"
#: OpenRouter routes this one to Amazon Bedrock, whose dialect is `cachePoint`.
REFUSING_MODEL = "openrouter/anthropic/claude-3-haiku"


def _provider(model: str, *, provider_name: str = "openrouter") -> LiteLLMProvider:
    client = LiteLLMProvider(api_key=OPENROUTER_KEY, default_model=model, provider_name=provider_name)
    client.generation = GenerationSettings(temperature=0, max_tokens=16, timeout=120)
    return client


def _messages(prompt: str = "Reply with the single word: ready.") -> list[dict]:
    return [{"role": "system", "content": FILLER}, {"role": "user", "content": prompt}]


async def _marked(model: str) -> tuple[list[dict], list[dict] | None]:
    """The payload as production sends it -- through the strategy that marks it."""
    from raven.token_wise.cache_optimizer import CacheOptimizer

    messages, tools, _ = await CacheOptimizer().before_llm_call(_messages(), None, model)
    return messages, tools


def _cached(response) -> int:
    usage = response.usage or {}
    return int(usage.get("cache_read_input_tokens") or usage.get("cached_tokens") or 0)


# ---------------------------------------------------------------------------
# The four routing shapes
# ---------------------------------------------------------------------------


@requires_openrouter
async def test_a_gateway_routed_id_reaches_the_upstream_vendor():
    """The prefix names the gateway, the rest names the vendor behind it."""
    response = await _provider(ANTHROPIC_MODEL).chat_with_retry(messages=_messages(), model=ANTHROPIC_MODEL)

    assert response.finish_reason != "error", response.content
    assert response.usage.get("prompt_tokens")


@requires_openrouter
async def test_a_bare_id_under_a_gateway_still_routes():
    """A stored id can be bare when the provider is pinned; the wire form has to
    put the gateway's prefix back on, or the request goes to the vendor direct
    with the gateway's key."""
    client = _provider(ANTHROPIC_MODEL)
    response = await client.chat_with_retry(messages=_messages(), model="anthropic/claude-fable-5")

    assert response.finish_reason != "error", response.content


@requires_openrouter
async def test_the_id_that_goes_out_is_the_one_wire_builds():
    """Asserted against the live call rather than against a recorded string.

    The baseline file is generated by the same code it checks, so it can only say
    the behaviour did not change -- never that it is right. A request that comes
    back at all is the vendor confirming the id resolved.
    """
    from raven.providers.wire import wire_model

    client = _provider(ANTHROPIC_MODEL)
    sent = client._resolve_model(ANTHROPIC_MODEL)

    assert sent == wire_model(ANTHROPIC_MODEL, gateway=client._gateway)
    response = await client.chat_with_retry(messages=_messages(), model=ANTHROPIC_MODEL)
    assert response.finish_reason != "error", response.content


# ---------------------------------------------------------------------------
# Cache breakpoints, as the vendor billed them
# ---------------------------------------------------------------------------


@requires_openrouter
async def test_an_anthropic_model_still_gets_its_cache_hit():
    """The half of the rule that must not regress.

    Marking is worth keeping for this family: with the field, the second turn
    reads nearly the whole prompt back from cache; without it, nothing is
    cached. A change that stops marking here is a change to a real bill.
    """
    client = _provider(ANTHROPIC_MODEL)
    messages, tools = await _marked(ANTHROPIC_MODEL)

    first = await client.chat_with_retry(messages=messages, tools=tools, model=ANTHROPIC_MODEL)
    assert first.finish_reason != "error", first.content
    second = await client.chat_with_retry(messages=messages, tools=tools, model=ANTHROPIC_MODEL)

    assert _cached(second) > 0, "the marked prefix was not read back from cache"


@requires_openrouter
async def test_a_non_anthropic_model_is_billed_the_same_marked_or_not():
    """The half of the rule that was costing money.

    OpenRouter accepts the field on every model it serves and forwards it to
    vendors that do not read it: a breakpoint on the last conversation message
    billed Gemini for nearly double the prompt tokens the same prompt costs
    unmarked. Marked and unmarked must now be indistinguishable, because the
    marker no longer fires for this family.
    """
    client = _provider(NON_ANTHROPIC_MODEL)
    marked_messages, marked_tools = await _marked(NON_ANTHROPIC_MODEL)

    assert "cache_control" not in str(marked_messages), "the strategy marked a family that does not read it"

    marked = await client.chat_with_retry(messages=marked_messages, tools=marked_tools, model=NON_ANTHROPIC_MODEL)
    plain = await client.chat_with_retry(messages=_messages(), model=NON_ANTHROPIC_MODEL)

    assert marked.usage.get("prompt_tokens") == plain.usage.get("prompt_tokens"), (
        f"marked={marked.usage} plain={plain.usage} -- the field is still reaching the vendor"
    )


@requires_openrouter
async def test_an_upstream_that_refuses_the_field_is_learned_from_once():
    """The failure no table could have predicted.

    Both catalogues correctly report that this model caches; what neither says is
    that OpenRouter routes it to Amazon Bedrock, whose dialect is ``cachePoint``.
    It answered 400 every turn. The first turn now pays one extra request and
    every turn after it is clean.
    """
    from raven.providers import prompt_cache

    prompt_cache.reset_suppressions()
    client = _provider(REFUSING_MODEL)

    for turn in range(3):
        messages, tools = await _marked(REFUSING_MODEL)
        response = await client.chat_with_retry(messages=messages, tools=tools, model=REFUSING_MODEL)
        assert response.finish_reason != "error", f"turn {turn}: {response.content}"

    assert prompt_cache.is_suppressed(REFUSING_MODEL), "the refusal was not learned"


# ---------------------------------------------------------------------------
# The credential probe, against a live endpoint
# ---------------------------------------------------------------------------


@requires_openrouter
async def test_the_probe_reports_a_live_gateway_as_usable():
    from raven.config.update_providers import test_provider as probe

    result = probe("openrouter", timeout_s=20)

    assert result["ok"] is True, result
    assert result["models_count"], result


async def test_a_provider_with_no_catalogue_endpoint_is_not_called_unconfigured(tmp_path):
    """Runs without any credential: the point is what the probe *says*, and it
    said `not_configured` for seven providers that were configured correctly."""
    from raven.config.update_providers import set_provider_fields
    from raven.config.update_providers import test_provider as probe

    config = tmp_path / "config.json"
    set_provider_fields("anthropic", {"api_key": "sk-probe"}, config_path=config)

    result = probe("anthropic", timeout_s=10, config_path=config)

    assert result["status"] == "no_probe_endpoint", result


# ---------------------------------------------------------------------------
# The streaming path, which is the one the TUI uses
# ---------------------------------------------------------------------------


@requires_openrouter
async def test_the_streaming_path_learns_the_refusal_too():
    """The learned downgrade lives in two places because the turn does.

    ``chat_with_retry`` covers the non-streaming callers; the TUI streams, and
    that path has no retry ladder at all -- a downgrade learned only behind the
    retry ladder never fires for the main interactive surface, and the affected
    model goes on answering 400 on every turn there.
    """
    from raven.providers import prompt_cache

    prompt_cache.reset_suppressions()
    client = _provider(REFUSING_MODEL)

    for turn in range(2):
        messages, tools = await _marked(REFUSING_MODEL)
        chunks = 0
        async for _ in client.chat_stream(messages=messages, tools=tools, model=REFUSING_MODEL, max_tokens=16):
            chunks += 1
        assert chunks, f"turn {turn} streamed nothing"

    assert prompt_cache.is_suppressed(REFUSING_MODEL)


@requires_openrouter
async def test_a_stream_that_completes_normally_still_yields_content():
    """The refusal retry reshaped the stream prologue; this is the plain path
    it must not disturb."""
    client = _provider(ANTHROPIC_MODEL)

    text = []
    async for delta in client.chat_stream(
        messages=[{"role": "user", "content": "Reply with the single word: ready."}],
        model=ANTHROPIC_MODEL,
        max_tokens=16,
    ):
        if delta.content:
            text.append(delta.content)

    assert "".join(text).strip(), "the stream produced no content"
