#!/usr/bin/env node

import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import {
  chmod,
  copyFile,
  lstat,
  mkdir,
  mkdtemp,
  open,
  readFile,
  readdir,
  realpath,
  rm,
  utimes,
  writeFile,
} from 'node:fs/promises';
import { readFileSync, realpathSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import {
  crc32,
  gzipSync,
  inflateRawSync,
} from 'node:zlib';
import {
  ActionRequiredError,
  RELEASE_VERSION,
  publicError,
  sanitizedChildEnv,
} from './lib.mjs';

const execFileAsync = promisify(execFile);
const FULL_PACKAGE_NAME = `erduo-broll-loop-engineering-${RELEASE_VERSION}`;
const STANDARD_PACKAGE_NAME = `erduo-broll-loop-engineering-skills-${RELEASE_VERSION}`;
const TAR_BLOCK_SIZE = 512;
const MAX_ARCHIVE_BYTES = 16 * 1024 * 1024;
const MAX_UNCOMPRESSED_BYTES = 128 * 1024 * 1024;
const MAX_TAR_RECORDS = 2_048;
const CANONICAL_MTIME_SECONDS = 946684800;
const CANONICAL_MTIME = new Date(CANONICAL_MTIME_SECONDS * 1000);
const SHOTCRAFT_ROOT = 'erduo-broll-loop-engineering/references/shotcraft';
const SHOTCRAFT_MANIFEST_FILE = `${SHOTCRAFT_ROOT}/manifest.json`;
const SHOTCRAFT_CATALOG_FILE = `${SHOTCRAFT_ROOT}/catalog.json`;
const SHOTCRAFT_ATTRIBUTION_FILE = `${SHOTCRAFT_ROOT}/upstream-attribution.md`;
const SHOTCRAFT_QUERY_FILE = 'erduo-broll-loop-engineering/scripts/query-shotcraft.mjs';
const SHOTCRAFT_LICENSE_FILE = 'third_party/licenses/video-shotcraft-APACHE-2.0.txt';
const DIAGRAM_DESIGN_LICENSE_FILE = 'third_party/licenses/diagram-design-MIT.txt';
const SHOTCRAFT_REMOTION_ROOT = `${SHOTCRAFT_ROOT}/remotion-sources`;
const SHOTCRAFT_REMOTION_MANIFEST_FILE = `${SHOTCRAFT_REMOTION_ROOT}/manifest.json`;
const SHOTCRAFT_UPSTREAM = Object.freeze({
  repository: 'https://github.com/Vincentwei1021/video-shotcraft',
  commit: '41ee360d82f4c491ba9d88a24a4add7d8ff1cf8b',
  libraryRevision: 'bdd94be16d60fa8f',
  license: 'Apache-2.0',
});
const SHOTCRAFT_ADAPTATION_NOTICE = 'Generated by erduo-broll-loop-engineering from the pinned '
  + 'video-shotcraft library metadata. Preview/media fields and demo, texture, audio, and TSX '
  + 'runtime assets are excluded. Copied Markdown card bodies are byte-identical to the pinned '
  + 'upstream sources.';
const SHOTCRAFT_CATALOG_SHA256 = 'ece17d1aa2b7d76b4f533f33d7127c61941de68927a9459000baf419593a4593';
const SHOTCRAFT_ATTRIBUTION_SHA256 = '3853b1a686e1ce3ad52884af392167c1e659a48da5b0d435f031386c738f1f0c';
const SHOTCRAFT_CARDS_AGGREGATE_SHA256 = '3372d5c434ce58b1c91de6b1b069102000f28dcac709feeda23ee55bee51506b';
const SHOTCRAFT_REMOTION_MANIFEST_SHA256 = 'ab6a3a82788f624678b7405399f4c71c50f227c7915ecd317c5d997441dc9e8c';

function loadShotcraftManifest(repoRoot) {
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(path.join(repoRoot, SHOTCRAFT_MANIFEST_FILE), 'utf8'));
  } catch {
    throw new ActionRequiredError(
      'release_shotcraft_manifest_invalid',
      'Shotcraft manifest is missing or invalid JSON.',
    );
  }
  if (manifest?.schemaVersion !== 1
    || manifest.adaptationNotice !== SHOTCRAFT_ADAPTATION_NOTICE
    || JSON.stringify(manifest.upstream) !== JSON.stringify(SHOTCRAFT_UPSTREAM)
    || manifest.stats?.cards !== 152
    || manifest.stats?.styles !== 209
    || manifest.catalog?.target !== SHOTCRAFT_CATALOG_FILE
    || manifest.attribution?.target !== SHOTCRAFT_ATTRIBUTION_FILE
    || !Array.isArray(manifest.cards)
    || manifest.cards.length !== 152) {
    throw new ActionRequiredError(
      'release_shotcraft_manifest_invalid',
      'Shotcraft manifest contract does not match the pinned catalog.',
    );
  }
  const cardTargets = [];
  const names = new Set();
  const targets = new Set([manifest.catalog.target, manifest.attribution.target]);
  for (const card of manifest.cards) {
    const expectedTarget = `${SHOTCRAFT_ROOT}/cards/${card?.category}/${card?.name}.md`;
    const expectedSource = `references/shots/${card?.category}/${card?.name}.md`;
    const expectedUpstreamUrl = `${SHOTCRAFT_UPSTREAM.repository}/blob/`
      + `${SHOTCRAFT_UPSTREAM.commit}/${expectedSource}`;
    if (!card || typeof card.name !== 'string'
      || !/^[a-z0-9][a-z0-9-]*$/u.test(card.name)
      || typeof card.category !== 'string'
      || !/^[a-z0-9][a-z0-9-]*$/u.test(card.category)
      || card.target !== expectedTarget
      || card.source !== expectedSource
      || card.upstreamUrl !== expectedUpstreamUrl
      || !Number.isSafeInteger(card.bytes) || card.bytes <= 0
      || typeof card.sha256 !== 'string' || !/^[a-f0-9]{64}$/u.test(card.sha256)
      || names.has(card.name) || targets.has(card.target)) {
      throw new ActionRequiredError(
        'release_shotcraft_manifest_invalid',
        'Shotcraft manifest contains an invalid or duplicate card entry.',
      );
    }
    names.add(card.name);
    targets.add(card.target);
    cardTargets.push(card.target);
  }
  for (const record of [manifest.catalog, manifest.attribution]) {
    if (!Number.isSafeInteger(record.bytes) || record.bytes <= 0
      || typeof record.sha256 !== 'string' || !/^[a-f0-9]{64}$/u.test(record.sha256)) {
      throw new ActionRequiredError(
        'release_shotcraft_manifest_invalid',
        'Shotcraft manifest contains an invalid catalog or attribution digest.',
      );
    }
  }
  return { manifest, cardTargets: cardTargets.toSorted() };
}

const MODULE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SHOTCRAFT_RELEASE = loadShotcraftManifest(MODULE_ROOT);

function loadShotcraftRemotionManifest(repoRoot) {
  let manifest;
  try {
    const manifestBody = readFileSync(path.join(repoRoot, SHOTCRAFT_REMOTION_MANIFEST_FILE));
    const manifestDigest = createHash('sha256').update(manifestBody).digest('hex');
    if (manifestDigest !== SHOTCRAFT_REMOTION_MANIFEST_SHA256) {
      throw new Error('pinned manifest digest mismatch');
    }
    manifest = JSON.parse(manifestBody.toString('utf8'));
  } catch {
    throw new ActionRequiredError(
      'release_shotcraft_remotion_manifest_invalid',
      'Shotcraft Remotion source manifest is missing or invalid JSON.',
    );
  }
  const repository = SHOTCRAFT_UPSTREAM.repository;
  const commit = SHOTCRAFT_UPSTREAM.commit;
  if (manifest?.schemaVersion !== 1
    || manifest.upstream?.repository !== repository
    || manifest.upstream?.commit !== commit
    || manifest.upstream?.license !== SHOTCRAFT_UPSTREAM.license
    || manifest.stats?.cards !== 152
    || !Number.isSafeInteger(manifest.stats?.sourceFiles)
    || manifest.stats.sourceFiles <= 0
    || !Array.isArray(manifest.files)
    || manifest.files.length !== manifest.stats.sourceFiles) {
    throw new ActionRequiredError(
      'release_shotcraft_remotion_manifest_invalid',
      'Shotcraft Remotion source manifest does not match its pinned source.',
    );
  }
  const fixed = [manifest.index, manifest.sourceDescription];
  const records = [...fixed, ...manifest.files];
  const targets = new Set();
  const sources = new Set();
  for (const record of records) {
    const target = record?.target;
    const relative = typeof target === 'string'
      ? path.relative(SHOTCRAFT_REMOTION_ROOT, target)
      : null;
    if (!record || typeof target !== 'string'
      || path.isAbsolute(target) || target.includes('\\')
      || !relative || path.isAbsolute(relative) || relative === '..'
      || relative.startsWith(`..${path.sep}`)
      || !Number.isSafeInteger(record.bytes) || record.bytes <= 0
      || typeof record.sha256 !== 'string' || !/^[a-f0-9]{64}$/u.test(record.sha256)
      || targets.has(target)) {
      throw new ActionRequiredError(
        'release_shotcraft_remotion_manifest_invalid',
        'Shotcraft Remotion manifest contains an invalid or duplicate target.',
      );
    }
    targets.add(target);
  }
  if (manifest.index.target !== `${SHOTCRAFT_REMOTION_ROOT}/index.json`
    || manifest.sourceDescription.target !== `${SHOTCRAFT_REMOTION_ROOT}/SOURCE.md`) {
    throw new ActionRequiredError(
      'release_shotcraft_remotion_manifest_invalid',
      'Shotcraft Remotion manifest metadata targets are invalid.',
    );
  }
  for (const record of manifest.files) {
    const expectedTarget = `${SHOTCRAFT_REMOTION_ROOT}/${record.source}`;
    const expectedUrl = `${repository}/blob/${commit}/${record.source}`;
    if (typeof record.source !== 'string' || path.isAbsolute(record.source)
      || record.source.includes('\\') || record.source.startsWith('../')
      || record.target !== expectedTarget || record.upstreamUrl !== expectedUrl
      || sources.has(record.source)) {
      throw new ActionRequiredError(
        'release_shotcraft_remotion_manifest_invalid',
        'Shotcraft Remotion manifest contains an invalid or duplicate source.',
      );
    }
    sources.add(record.source);
  }
  return {
    manifest,
    records,
    releaseFiles: [SHOTCRAFT_REMOTION_MANIFEST_FILE, ...targets].toSorted(),
  };
}

const SHOTCRAFT_REMOTION_RELEASE = loadShotcraftRemotionManifest(MODULE_ROOT);

const ROOT_FILES = [
  '.gitignore',
  'CHANGELOG.md',
  'CONTRIBUTING.md',
  'docs/LEAN-WORKFLOW-VALIDATION.md',
  'docs/V1.0.0-BENCHMARK.md',
  'docs/V1.0.0-DESIGN.md',
  'Install.command',
  'LICENSE',
  'PRIVACY.md',
  'README.md',
  'README.en.md',
  'README.ja.md',
  'README.ko.md',
  'README.zh-TW.md',
  'SECURITY.md',
  'SUPPORT-MATRIX.md',
  'THIRD-PARTY-NOTICES.md',
  'package.json',
  'runtime/package.json',
  'runtime/package-lock.json',
];

const SCRIPT_FILES = [
  'scripts/config.mjs',
  'scripts/doctor.mjs',
  'scripts/install.mjs',
  'scripts/lib.mjs',
  'scripts/production-preflight.mjs',
  'scripts/uninstall.mjs',
];

const SKILL_FILES = [
  'erduo-broll-loop-engineering/SKILL.md',
  'erduo-broll-loop-engineering/agents/openai.yaml',
  'erduo-broll-loop-engineering/references/legacy-production.md',
  'erduo-broll-loop-engineering/references/lean-production.md',
  'erduo-broll-loop-engineering/references/lean-visual-direction.md',
  'erduo-broll-loop-engineering/scripts/lean-plan.mjs',
  'erduo-broll-loop-engineering/scripts/lean-render.mjs',
  'erduo-broll-loop-engineering/references/creative-director.md',
  'erduo-broll-loop-engineering/references/creative-creator.md',
  'erduo-broll-loop-engineering/references/creative-reviewer.md',
  'erduo-broll-loop-engineering/references/motion-patterns.md',
  'erduo-broll-loop-engineering/assets/motion-starter.html',
  'erduo-broll-loop-engineering/scripts/prepare-creative-task.mjs',
  'erduo-broll-loop-engineering/references/animation-craft.md',
  'erduo-broll-loop-engineering/references/visual-craft.md',
  'erduo-broll-loop-engineering/references/first-run-onboarding.md',
  'erduo-broll-loop-engineering/references/handoff-template.md',
  'erduo-broll-loop-engineering/references/motion-layout-lint.md',
  'erduo-broll-loop-engineering/references/parent-review-checklist.md',
  'erduo-broll-loop-engineering/references/prompt-first-workflow.md',
  'erduo-broll-loop-engineering/references/roles/role-charters.json',
  'erduo-broll-loop-engineering/references/safe-execution.md',
  'erduo-broll-loop-engineering/references/stage-orchestration.md',
  'erduo-broll-loop-engineering/references/runtime/capability-matrix.json',
  'erduo-broll-loop-engineering/references/runtime/canary-technical-gate.schema.json',
  'erduo-broll-loop-engineering/references/runtime/canary-user-decision.schema.json',
  'erduo-broll-loop-engineering/references/runtime/chapter-creative-receipt.schema.json',
  'erduo-broll-loop-engineering/references/runtime/frozen-block.schema.json',
  'erduo-broll-loop-engineering/references/runtime/delivery-index.schema.json',
  'erduo-broll-loop-engineering/references/runtime/motion-map.schema.json',
  'erduo-broll-loop-engineering/references/runtime/production-event.schema.json',
  'erduo-broll-loop-engineering/references/runtime/production-metrics.schema.json',
  'erduo-broll-loop-engineering/references/runtime/motion-layout-trace.schema.json',
  'erduo-broll-loop-engineering/references/runtime/remotion-hyperframes-map.md',
  'erduo-broll-loop-engineering/references/runtime/runtime-contract.md',
  'erduo-broll-loop-engineering/references/runtime/runtime-selection.schema.json',
  'erduo-broll-loop-engineering/references/runtime/runtime-selection.md',
  'erduo-broll-loop-engineering/references/runtime/runtime-plan.schema.json',
  'erduo-broll-loop-engineering/references/runtime/runtime-plan-v3.schema.json',
  'erduo-broll-loop-engineering/references/runtime/runtime-plan-v1.schema.json',
  'erduo-broll-loop-engineering/references/runtime/representative-scenes.schema.json',
  'erduo-broll-loop-engineering/references/runtime/shot-recipe.schema.json',
  'erduo-broll-loop-engineering/references/runtime/shot-recipe-v3.schema.json',
  'erduo-broll-loop-engineering/references/runtime/shot-recipe-v1.schema.json',
  'erduo-broll-loop-engineering/references/runtime/shot-recipe-v2.schema.json',
  'erduo-broll-loop-engineering/references/runtime/narrative-envelope.schema.json',
  'erduo-broll-loop-engineering/references/runtime/visual-system.schema.json',
  'erduo-broll-loop-engineering/references/runtime/visual-lock.schema.json',
  'erduo-broll-loop-engineering/references/runtime/shot-pattern.schema.json',
  'erduo-broll-loop-engineering/references/runtime/shot-media.schema.json',
  'erduo-broll-loop-engineering/references/runtime/remotion-project.schema.json',
  'erduo-broll-loop-engineering/references/remotion-backend.md',
  'erduo-broll-loop-engineering/scripts/detect-runtime.mjs',
  'erduo-broll-loop-engineering/scripts/config.mjs',
  'erduo-broll-loop-engineering/scripts/doctor.mjs',
  'erduo-broll-loop-engineering/scripts/lib.mjs',
  'erduo-broll-loop-engineering/scripts/production-preflight.mjs',
  'erduo-broll-loop-engineering/scripts/assemble-frozen-production.mjs',
  'erduo-broll-loop-engineering/scripts/collect-production-metrics.mjs',
  'erduo-broll-loop-engineering/scripts/create-production-profile.mjs',
  'erduo-broll-loop-engineering/scripts/frozen-media-policy.mjs',
  'erduo-broll-loop-engineering/scripts/gate-builder-assignment.mjs',
  'erduo-broll-loop-engineering/scripts/generate-role-files.mjs',
  'erduo-broll-loop-engineering/scripts/motion-layout-lint.mjs',
  'erduo-broll-loop-engineering/scripts/remotion-dom-trace.mjs',
  'erduo-broll-loop-engineering/scripts/remotion-toolchain.mjs',
  'erduo-broll-loop-engineering/scripts/record-production-event.mjs',
  'erduo-broll-loop-engineering/scripts/plan-runtime.mjs',
  'erduo-broll-loop-engineering/scripts/render-assigned-shots.mjs',
  'erduo-broll-loop-engineering/scripts/assemble-shot-preview.mjs',
  'erduo-broll-loop-engineering/scripts/backend-inspection.mjs',
  'erduo-broll-loop-engineering/scripts/shot-media-lib.mjs',
  'erduo-broll-loop-engineering/scripts/query-craft.mjs',
  'erduo-broll-loop-engineering/scripts/craft-catalog.mjs',
  'erduo-broll-loop-engineering/scripts/runtime-schema-validator.mjs',
  'erduo-broll-loop-engineering/scripts/remotion-verify.mjs',
  'erduo-broll-loop-engineering/scripts/validate-shot-recipes.mjs',
  'erduo-broll-loop-engineering/scripts/validate-motion-map.mjs',
  'erduo-broll-loop-engineering/scripts/validate-shot-media.mjs',
  'erduo-broll-loop-engineering/scripts/validate-runtime-plan.mjs',
  'erduo-broll-loop-engineering/scripts/validate-visual-lock.mjs',
  'erduo-broll-loop-engineering/scripts/validate-frozen-blocks.mjs',
  'erduo-broll-loop-engineering/scripts/verify-lightweight-codec.mjs',
  'erduo-broll-loop-engineering/scripts/safe-spawn.mjs',
  'erduo-broll-loop-engineering/references/craft/catalog.json',
  'erduo-broll-loop-engineering/references/craft/attribution-manifest.json',
  SHOTCRAFT_MANIFEST_FILE,
  SHOTCRAFT_CATALOG_FILE,
  SHOTCRAFT_ATTRIBUTION_FILE,
  SHOTCRAFT_QUERY_FILE,
  ...SHOTCRAFT_RELEASE.cardTargets,
  ...SHOTCRAFT_REMOTION_RELEASE.releaseFiles,
  ...[
    'broll-onboarding',
    'broll-director',
    'broll-assets',
    'broll-master-build',
    'broll-master-integrate',
    'broll-render',
    'broll-shot-export',
    'broll-remotion-build',
    'broll-remotion-integrate',
    'broll-remotion-render',
    'broll-runtime-plan',
    'broll-hybrid-integrate',
    'broll-hybrid-render',
  ].flatMap((name) => [
    `erduo-broll-loop-engineering/stages/${name}/SKILL.md`,
    `erduo-broll-loop-engineering/stages/${name}/agents/openai.yaml`,
  ]),
  'erduo-broll-loop-engineering/stages/broll-director/AGENTS.md',
  'erduo-broll-loop-engineering/stages/broll-director/CLAUDE.md',
  'erduo-broll-loop-engineering/stages/broll-director/role-prompt.md',
  'erduo-broll-loop-engineering/stages/broll-master-build/AGENTS.md',
  'erduo-broll-loop-engineering/stages/broll-master-build/CLAUDE.md',
  'erduo-broll-loop-engineering/stages/broll-master-build/role-prompts/lead.md',
  'erduo-broll-loop-engineering/stages/broll-master-build/role-prompts/builder.md',
  'erduo-broll-loop-engineering/stages/broll-remotion-build/AGENTS.md',
  'erduo-broll-loop-engineering/stages/broll-remotion-build/CLAUDE.md',
  'erduo-broll-loop-engineering/stages/broll-remotion-build/role-prompts/lead.md',
  'erduo-broll-loop-engineering/stages/broll-remotion-build/role-prompts/builder.md',
];

export const RELEASE_FILES = Object.freeze([
  ...ROOT_FILES,
  ...SCRIPT_FILES,
  ...SKILL_FILES,
  DIAGRAM_DESIGN_LICENSE_FILE,
  SHOTCRAFT_LICENSE_FILE,
].toSorted());

const STANDARD_ONLY_EXCLUSIONS = new Set([
  'Install.command',
  'package.json',
  'runtime/package.json',
  'runtime/package-lock.json',
  'scripts/install.mjs',
  'scripts/uninstall.mjs',
]);

export const STANDARD_RELEASE_FILES = Object.freeze(
  RELEASE_FILES.filter((file) => !STANDARD_ONLY_EXCLUSIONS.has(file)),
);

function releaseProfile(profile = 'full') {
  if (profile === 'full') {
    return Object.freeze({ name: FULL_PACKAGE_NAME, files: RELEASE_FILES, profile });
  }
  if (profile === 'standard') {
    return Object.freeze({ name: STANDARD_PACKAGE_NAME, files: STANDARD_RELEASE_FILES, profile });
  }
  throw new ActionRequiredError('usage', 'Release profile must be full or standard.');
}

const REPOSITORY_DEMO_FILES = Object.freeze([
  'docs/images/demos/homepage-showcase.gif',
  'docs/images/demos/quick-start.gif',
]);

export const REPOSITORY_ONLY_FILES = Object.freeze([
  '.github/workflows/ci.yml',
  'RELEASE-CHECKLIST.md',
  ...REPOSITORY_DEMO_FILES,
  'docs/V0.8.0-CONTEXT-MEASUREMENT.json',
  'docs/V0.8.0-IMPLEMENTATION-PLAN.md',
  'docs/V0.9.0-DESIGN.md',
  'docs/images/wechat-contact.jpg',
  'docs/images/workflow-zh.svg',
  'scripts/sync-video-shotcraft.mjs',
  'scripts/sync-video-shotcraft-remotion.mjs',
  'scripts/measure-context.mjs',
  'scripts/lean-plan.test.mjs',
  'scripts/lean-render.test.mjs',
  'scripts/prepare-creative-task.test.mjs',
  'scripts/metrics-media.test.mjs',
  'scripts/creative-loop-delivery.test.mjs',
  'scripts/creative-loop-planner.test.mjs',
  'scripts/creative-loop-roles.test.mjs',
  'scripts/motion-layout-lint.test.mjs',
  'scripts/package-release.mjs',
  'scripts/remotion-dom-trace.e2e.test.mjs',
  'scripts/remotion-canary.e2e.test.mjs',
  'scripts/role-motion-map.test.mjs',
  'scripts/shot-native-delivery.test.mjs',
  'scripts/v1-planner-visual-lock.test.mjs',
  'scripts/fixtures/remotion-dom-trace/package.json',
  'scripts/fixtures/remotion-dom-trace/package-lock.json',
  'scripts/fixtures/remotion-dom-trace/tsconfig.json',
  'scripts/fixtures/remotion-dom-trace/src/index.tsx',
  'scripts/fixtures/remotion-dom-trace/src/inspection.tsx',
  'scripts/fixtures/remotion-dom-trace/src/root.tsx',
  'scripts/fixtures/runtime-plan-v2/history.json',
  'scripts/test.mjs',
].toSorted());

const LOCAL_ONLY_FILES = new Set([
  'docs/V1.0.0-IMPLEMENTATION-PR.md',
  'docs/V1.0.1-PR-SPEC.md',
  'docs/V1.0.1-CREATIVE-LOOP-RESET-PR-SPEC.md',
]);

const SENSITIVE_EXTENSIONS = /\.(?:srt|vtt|jpg|jpeg|png|gif|webp|heic|mp4|mov|mkv|webm|avi|mp3|wav|m4a|pem|key|p12|pfx)$/iu;
const SENSITIVE_NAMES = /(?:^|\/)(?:\.env(?:\..*)?|cookies?(?:\..*)?|\.netrc)$/iu;
const PRIVATE_PATHS = [
  /\/Users\/[^/\s]+/u,
  /\/home\/[^/\s]+/u,
  /[A-Za-z]:\\Users\\/u,
];
const CREDENTIAL_PATTERNS = [
  /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/u,
  /\b(?:AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{35})\b/u,
  /\b(?:sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|npm_[A-Za-z0-9]{20,})\b/u,
  /(?:^|[\s,{])["']?(?:api[_-]?key|token|secret|password)["']?\s*[:=]\s*(?:"[^"\r\n]{8,}"|'[^'\r\n]{8,}'|[^\s"'#,}\]]{8,})(?=$|[\s,}\]])/imu,
  /(?:^|[\s,{])["']?(?:PEXELS_API_KEY|OPENAI_API_KEY|ANTHROPIC_API_KEY|GITHUB_TOKEN|NPM_TOKEN|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|GOOGLE_API_KEY|[A-Z][A-Z0-9_]*(?:_KEY|_TOKEN|_PASSWORD|_SECRET))["']?\s*[:=]\s*(?:"[A-Za-z0-9._~+/=-]{8,}"|'[A-Za-z0-9._~+/=-]{8,}'|[A-Za-z0-9._~+/=-]{8,})(?=$|[\s,}\]])/imu,
];

function isWithin(parent, child) {
  const relative = path.relative(parent, child);
  return relative !== '' && !path.isAbsolute(relative)
    && relative !== '..' && !relative.startsWith(`..${path.sep}`);
}

async function sourceFiles(repoRoot) {
  const files = [];
  async function visit(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.name === '.git' || entry.name === 'node_modules') continue;
      if (entry.name === '.DS_Store') continue;
      const absolute = path.join(directory, entry.name);
      if (LOCAL_ONLY_FILES.has(path.relative(repoRoot, absolute))) continue;
      if (entry.isSymbolicLink()) {
        throw new ActionRequiredError(
          'release_symlink_forbidden',
          'Release source contains a symbolic link.',
        );
      }
      if (entry.isDirectory()) await visit(absolute);
      else if (entry.isFile()) files.push(path.relative(repoRoot, absolute));
      else {
        throw new ActionRequiredError(
          'release_special_file_forbidden',
          'Release source contains a non-regular file.',
        );
      }
    }
  }
  await visit(repoRoot);
  return files.toSorted();
}

async function validateShotcraftRelease(repoRoot) {
  const { manifest } = loadShotcraftManifest(repoRoot);
  const cardDigestList = manifest.cards
    .toSorted((left, right) => left.target.localeCompare(right.target))
    .map((record) => `${record.sha256}  ${record.target}\n`)
    .join('');
  if (manifest.catalog.sha256 !== SHOTCRAFT_CATALOG_SHA256
    || manifest.attribution.sha256 !== SHOTCRAFT_ATTRIBUTION_SHA256
    || createHash('sha256').update(cardDigestList).digest('hex')
      !== SHOTCRAFT_CARDS_AGGREGATE_SHA256) {
    throw new ActionRequiredError(
      'release_shotcraft_manifest_invalid',
      'Shotcraft pinned catalog or aggregate card digest has drifted.',
    );
  }
  const records = [manifest.catalog, manifest.attribution, ...manifest.cards];
  for (const record of records) {
    const absolute = path.join(repoRoot, record.target);
    const info = await lstat(absolute);
    if (!info.isFile() || info.isSymbolicLink()
      || info.size !== record.bytes
      || await hashFile(absolute) !== record.sha256) {
      throw new ActionRequiredError(
        'release_shotcraft_manifest_invalid',
        `Shotcraft manifest digest mismatch for ${record.target}.`,
      );
    }
  }

  let catalog;
  try {
    catalog = JSON.parse(await readFile(path.join(repoRoot, SHOTCRAFT_CATALOG_FILE), 'utf8'));
  } catch {
    throw new ActionRequiredError(
      'release_shotcraft_catalog_invalid',
      'Shotcraft catalog is missing or invalid JSON.',
    );
  }
  if (catalog?.schemaVersion !== 1
    || catalog.adaptationNotice !== SHOTCRAFT_ADAPTATION_NOTICE
    || JSON.stringify(catalog.upstream) !== JSON.stringify(SHOTCRAFT_UPSTREAM)
    || catalog.stats?.cards !== 152 || catalog.stats?.styles !== 209
    || !Array.isArray(catalog.cards) || catalog.cards.length !== 152) {
    throw new ActionRequiredError(
      'release_shotcraft_catalog_invalid',
      'Shotcraft catalog contract does not match its pinned source.',
    );
  }
  const manifestByName = new Map(manifest.cards.map((record) => [record.name, record]));
  const names = new Set();
  const styleKeys = new Set();
  for (const card of catalog.cards) {
    const record = manifestByName.get(card?.name);
    const localSource = `cards/${card?.category}/${card?.name}.md`;
    if (!record || names.has(card.name)
      || card.category !== record.category
      || card.source !== record.source
      || card.upstreamUrl !== record.upstreamUrl
      || card.localSource !== localSource
      || !Array.isArray(card.styles) || card.styles.length === 0) {
      throw new ActionRequiredError(
        'release_shotcraft_catalog_invalid',
        'Shotcraft catalog contains an invalid or unbound card.',
      );
    }
    names.add(card.name);
    for (const style of card.styles) {
      if (!style || typeof style.key !== 'string' || style.key === ''
        || styleKeys.has(style.key)) {
        throw new ActionRequiredError(
          'release_shotcraft_catalog_invalid',
          'Shotcraft catalog contains an invalid or duplicate style key.',
        );
      }
      styleKeys.add(style.key);
    }
  }
  if (names.size !== 152 || styleKeys.size !== 209
    || names.size !== manifestByName.size) {
    throw new ActionRequiredError(
      'release_shotcraft_catalog_invalid',
      'Shotcraft catalog counts do not close over the manifest.',
    );
  }

  const licensePath = path.join(repoRoot, SHOTCRAFT_LICENSE_FILE);
  const license = await readFile(licensePath, 'utf8');
  if (Buffer.byteLength(license) !== 11340
    || await hashFile(licensePath) !== 'b2ce9877a55547ada9b870150664d1468ff777e67cc9888806a73927d31c5771'
    || !license.includes('Apache License\n                           Version 2.0, January 2004')) {
    throw new ActionRequiredError(
      'release_shotcraft_license_invalid',
      'Bundled video-shotcraft Apache-2.0 license text is incomplete or modified.',
    );
  }
}

async function validateShotcraftRemotionRelease(repoRoot) {
  const { records, releaseFiles } = loadShotcraftRemotionManifest(repoRoot);
  for (const record of records) {
    const absolute = path.join(repoRoot, record.target);
    let info;
    try {
      info = await lstat(absolute);
    } catch {
      throw new ActionRequiredError(
        'release_shotcraft_remotion_manifest_invalid',
        `Shotcraft Remotion manifest target is missing: ${record.target}.`,
      );
    }
    if (!info.isFile() || info.isSymbolicLink()
      || info.size !== record.bytes
      || await hashFile(absolute) !== record.sha256) {
      throw new ActionRequiredError(
        'release_shotcraft_remotion_manifest_invalid',
        `Shotcraft Remotion manifest digest mismatch for ${record.target}.`,
      );
    }
  }
  const sourceRoot = path.join(repoRoot, SHOTCRAFT_REMOTION_ROOT);
  const actual = [];
  async function visit(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const target = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) {
        throw new ActionRequiredError(
          'release_shotcraft_remotion_manifest_invalid',
          'Shotcraft Remotion source closure contains a symbolic link.',
        );
      }
      if (entry.isDirectory()) await visit(target);
      else if (entry.isFile()) actual.push(path.relative(repoRoot, target));
      else {
        throw new ActionRequiredError(
          'release_shotcraft_remotion_manifest_invalid',
          'Shotcraft Remotion source closure contains a special file.',
        );
      }
    }
  }
  await visit(sourceRoot);
  if (JSON.stringify(actual.toSorted()) !== JSON.stringify(releaseFiles)) {
    throw new ActionRequiredError(
      'release_shotcraft_remotion_manifest_invalid',
      'Shotcraft Remotion source directory does not close over its manifest.',
    );
  }
}

async function validateSource(repoRoot) {
  await validateShotcraftRelease(repoRoot);
  await validateShotcraftRemotionRelease(repoRoot);
  const actual = await sourceFiles(repoRoot);
  const packagedSource = actual.includes('SHA256SUMS.txt');
  const repositoryFiles = packagedSource
    ? [...RELEASE_FILES, 'SHA256SUMS.txt'].toSorted()
    : [...RELEASE_FILES, ...REPOSITORY_ONLY_FILES].toSorted();
  const allowed = new Set(repositoryFiles);
  const extra = actual.filter((file) => !allowed.has(file));
  const missing = repositoryFiles.filter((file) => !actual.includes(file));
  if (extra.length || missing.length) {
    throw new ActionRequiredError(
      'release_file_set_mismatch',
      `Release file whitelist mismatch: extra=${extra.length}, missing=${missing.length}.`,
    );
  }

  for (const relative of RELEASE_FILES) {
    if (SENSITIVE_EXTENSIONS.test(relative) || SENSITIVE_NAMES.test(relative)) {
      throw new ActionRequiredError(
        'release_sensitive_file_forbidden',
        'Release whitelist contains a sensitive filename or media type.',
      );
    }
    const text = await readFile(path.join(repoRoot, relative), 'utf8');
    const privatePattern = PRIVATE_PATHS.findIndex((pattern) => pattern.test(text));
    const credentialPattern = CREDENTIAL_PATTERNS.findIndex((pattern) => pattern.test(text));
    if (privatePattern !== -1 || credentialPattern !== -1) {
      throw new ActionRequiredError(
        'release_sensitive_content_forbidden',
        `Release source contains sensitive content in ${relative} `
          + `(path-rule=${privatePattern}, credential-rule=${credentialPattern}).`,
      );
    }
  }

  if (!packagedSource) {
    const workflow = await readFile(
      path.join(repoRoot, 'docs/images/workflow-zh.svg'),
      'utf8',
    );
    if (!workflow.startsWith('<svg ') || !workflow.includes('</svg>')
      || Buffer.byteLength(workflow) > 512 * 1024
      || PRIVATE_PATHS.some((pattern) => pattern.test(workflow))
      || CREDENTIAL_PATTERNS.some((pattern) => pattern.test(workflow))) {
      throw new ActionRequiredError(
        'release_repository_asset_invalid',
        'Repository workflow image failed its bounded SVG validation.',
      );
    }

    const contact = await readFile(
      path.join(repoRoot, 'docs/images/wechat-contact.jpg'),
    );
    if (contact.length < 4 || contact.length > 2 * 1024 * 1024
      || contact[0] !== 0xff || contact[1] !== 0xd8
      || contact.at(-2) !== 0xff || contact.at(-1) !== 0xd9) {
      throw new ActionRequiredError(
        'release_repository_asset_invalid',
        'Repository contact image failed its bounded JPEG validation.',
      );
    }

    for (const relative of REPOSITORY_DEMO_FILES) {
      const demo = await readFile(path.join(repoRoot, relative));
      const header = demo.subarray(0, 6).toString('ascii');
      if (demo.length < 32 || demo.length > 8 * 1024 * 1024
        || !['GIF87a', 'GIF89a'].includes(header)
        || demo.at(-1) !== 0x3b) {
        throw new ActionRequiredError(
          'release_repository_asset_invalid',
          `Repository demo animation failed bounded GIF validation: ${relative}.`,
        );
      }
    }
  }
}

async function hashFile(file) {
  return createHash('sha256').update(await readFile(file)).digest('hex');
}

async function writeChecksums(packageRoot, releaseFiles = RELEASE_FILES) {
  const lines = [];
  for (const relative of releaseFiles) {
    lines.push(`${await hashFile(path.join(packageRoot, relative))}  ${relative}`);
  }
  const file = path.join(packageRoot, 'SHA256SUMS.txt');
  await writeFile(
    file,
    `${lines.join('\n')}\n`,
    { encoding: 'utf8', mode: 0o644, flag: 'wx' },
  );
  return file;
}

function releaseChildEnv(env) {
  const childEnv = sanitizedChildEnv(env);
  for (const key of Object.keys(childEnv)) {
    if (key.toUpperCase() === 'COPYFILE_DISABLE') delete childEnv[key];
  }
  childEnv.COPYFILE_DISABLE = '1';
  return childEnv;
}

function archiveError(code = 'release_archive_invalid') {
  const messages = {
    release_archive_appledouble_forbidden: 'Archive contains forbidden AppleDouble metadata.',
    release_archive_members_mismatch: 'Archive members do not match the release whitelist.',
    release_archive_checksum_invalid: 'Archive checksum verification failed.',
  };
  return new ActionRequiredError(
    code,
    messages[code] || 'Archive failed strict raw tar validation.',
  );
}

function isZeroBlock(buffer, offset) {
  for (let index = offset; index < offset + TAR_BLOCK_SIZE; index += 1) {
    if (buffer[index] !== 0) return false;
  }
  return true;
}

function parseTarNumber(field) {
  if (field[0] & 0x80) {
    if (field[0] & 0x40) throw archiveError();
    let value = BigInt(field[0] & 0x3f);
    for (const byte of field.subarray(1)) value = (value << 8n) | BigInt(byte);
    if (value > BigInt(Number.MAX_SAFE_INTEGER)) throw archiveError();
    return Number(value);
  }
  const text = field.toString('ascii').replace(/[\0 ]+$/u, '').trimStart();
  if (text === '') return 0;
  if (!/^[0-7]+$/u.test(text)) throw archiveError();
  const value = Number.parseInt(text, 8);
  if (!Number.isSafeInteger(value) || value < 0) throw archiveError();
  return value;
}

function decodeTarField(field) {
  const nul = field.indexOf(0);
  const content = nul === -1 ? field : field.subarray(0, nul);
  if (nul !== -1 && field.subarray(nul).some((byte) => byte !== 0)) {
    throw archiveError();
  }
  try {
    return new TextDecoder('utf-8', { fatal: true }).decode(content);
  } catch {
    throw archiveError();
  }
}

function verifyTarHeaderChecksum(header) {
  const stored = parseTarNumber(header.subarray(148, 156));
  let calculated = 0;
  for (let index = 0; index < TAR_BLOCK_SIZE; index += 1) {
    calculated += index >= 148 && index < 156 ? 0x20 : header[index];
  }
  if (stored !== calculated) throw archiveError();
}

function validateMemberPath(rawPath, type, profile = releaseProfile()) {
  if (typeof rawPath !== 'string' || rawPath === '' || rawPath.includes('\0')
    || rawPath.includes('\\') || rawPath.startsWith('/') || rawPath.includes('//')
    || rawPath.normalize('NFC') !== rawPath) {
    throw archiveError();
  }
  const directory = type === 'directory';
  if (directory !== rawPath.endsWith('/')) throw archiveError();
  const logical = directory ? rawPath.slice(0, -1) : rawPath;
  const parts = logical.split('/');
  if (!logical || parts.some((part) => part === '' || part === '.' || part === '..')) {
    throw archiveError();
  }
  if (parts.some((part) => part.startsWith('._') || part.toUpperCase() === '__MACOSX')) {
    throw archiveError('release_archive_appledouble_forbidden');
  }
  if (parts[0] !== profile.name) throw archiveError('release_archive_members_mismatch');
  return logical;
}

function rejectAppleDoublePath(rawPath) {
  const parts = rawPath.split('/');
  if (parts.some((part) => part.startsWith('._') || part.toUpperCase() === '__MACOSX')) {
    throw archiveError('release_archive_appledouble_forbidden');
  }
}

function expectedArchiveMembers(profile = releaseProfile()) {
  const files = [...profile.files, 'SHA256SUMS.txt']
    .map((relative) => `${profile.name}/${relative}`)
    .toSorted();
  const directories = new Set([profile.name]);
  for (const file of files) {
    let current = path.posix.dirname(file);
    while (current !== '.') {
      directories.add(current);
      if (current === profile.name) break;
      current = path.posix.dirname(current);
    }
  }
  return { files, directories: [...directories].toSorted() };
}

async function readBoundedRegularFile(file, limit, {
  lstatImpl = lstat,
  openImpl = open,
  allocate = Buffer.allocUnsafe,
} = {}) {
  let before;
  try {
    before = await lstatImpl(file);
  } catch {
    throw archiveError();
  }
  if (before.isSymbolicLink() || !before.isFile() || !Number.isSafeInteger(before.size)
    || before.size <= 0 || before.size > limit) {
    throw archiveError();
  }

  let handle;
  try {
    handle = await openImpl(
      file,
      constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0),
    );
    const opened = await handle.stat();
    if (!opened.isFile() || opened.dev !== before.dev || opened.ino !== before.ino
      || opened.size !== before.size || opened.size > limit) {
      throw archiveError();
    }
    const buffer = allocate(opened.size);
    if (!Buffer.isBuffer(buffer) || buffer.length !== opened.size) throw archiveError();
    let offset = 0;
    while (offset < buffer.length) {
      const { bytesRead } = await handle.read(
        buffer,
        offset,
        buffer.length - offset,
        offset,
      );
      if (!Number.isInteger(bytesRead) || bytesRead <= 0) throw archiveError();
      offset += bytesRead;
    }
    const after = await handle.stat();
    if (after.dev !== opened.dev || after.ino !== opened.ino || after.size !== opened.size) {
      throw archiveError();
    }
    return buffer;
  } catch (error) {
    if (error instanceof ActionRequiredError) throw error;
    throw archiveError();
  } finally {
    await handle?.close().catch(() => {});
  }
}

function verifyCanonicalGzipHeader(compressed) {
  if (compressed.length < 18
    || compressed[0] !== 0x1f || compressed[1] !== 0x8b || compressed[2] !== 0x08
    || compressed[3] !== 0
    || compressed.readUInt32LE(4) !== 0
    || compressed[8] !== 2
    || compressed[9] !== 255) {
    throw archiveError();
  }
}

function decompressSingleCanonicalGzip(compressed) {
  verifyCanonicalGzipHeader(compressed);
  let inflated;
  try {
    inflated = inflateRawSync(compressed.subarray(10), {
      info: true,
      maxOutputLength: MAX_UNCOMPRESSED_BYTES,
    });
  } catch {
    throw archiveError();
  }
  const consumed = inflated?.engine?.bytesWritten;
  const tar = inflated?.buffer;
  if (!Buffer.isBuffer(tar) || !Number.isSafeInteger(consumed) || consumed <= 0) {
    throw archiveError();
  }
  const footerOffset = 10 + consumed;
  if (footerOffset + 8 !== compressed.length
    || compressed.readUInt32LE(footerOffset) !== (crc32(tar) >>> 0)
    || compressed.readUInt32LE(footerOffset + 4) !== (tar.length >>> 0)) {
    throw archiveError();
  }
  return tar;
}

function verifyChecksumManifest(contents, regularContents, profile = releaseProfile()) {
  let text;
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(contents);
  } catch {
    throw archiveError('release_archive_checksum_invalid');
  }
  if (!text.endsWith('\n')) throw archiveError('release_archive_checksum_invalid');
  const lines = text.slice(0, -1).split('\n');
  if (lines.length !== profile.files.length) {
    throw archiveError('release_archive_checksum_invalid');
  }
  const seen = new Set();
  for (const line of lines) {
    const match = /^([0-9a-f]{64})  (.+)$/u.exec(line);
    const relative = match?.[2];
    const archivePath = relative ? `${profile.name}/${relative}` : '';
    const body = regularContents.get(archivePath);
    if (!match || seen.has(relative) || !profile.files.includes(relative) || !body
      || createHash('sha256').update(body).digest('hex') !== match[1]) {
      throw archiveError('release_archive_checksum_invalid');
    }
    seen.add(relative);
  }
  if (JSON.stringify([...seen].toSorted()) !== JSON.stringify(profile.files)) {
    throw archiveError('release_archive_checksum_invalid');
  }
  return seen.size;
}

export async function verifyReleaseArchiveRaw(archive, io = {}, profileName = 'full') {
  const profile = releaseProfile(profileName);
  const compressed = await readBoundedRegularFile(archive, MAX_ARCHIVE_BYTES, io);
  const tar = decompressSingleCanonicalGzip(compressed);
  if (tar.length < TAR_BLOCK_SIZE * 2 || tar.length % TAR_BLOCK_SIZE !== 0) {
    throw archiveError();
  }

  const files = [];
  const directories = [];
  const regularContents = new Map();
  const collisionKeys = new Set();
  let offset = 0;
  let records = 0;
  let ended = false;

  while (offset < tar.length) {
    if (records >= MAX_TAR_RECORDS) throw archiveError();
    if (isZeroBlock(tar, offset)) {
      if (offset + TAR_BLOCK_SIZE * 2 > tar.length
        || !isZeroBlock(tar, offset + TAR_BLOCK_SIZE)) throw archiveError();
      for (let tail = offset + TAR_BLOCK_SIZE * 2; tail < tar.length; tail += 1) {
        if (tar[tail] !== 0) throw archiveError();
      }
      ended = true;
      break;
    }

    const header = tar.subarray(offset, offset + TAR_BLOCK_SIZE);
    if (header.length !== TAR_BLOCK_SIZE) throw archiveError();
    verifyTarHeaderChecksum(header);
    if (decodeTarField(header.subarray(257, 263)) !== 'ustar'
      || decodeTarField(header.subarray(263, 265)) !== '00'
      || header.subarray(500, 512).some((byte) => byte !== 0)) {
      throw archiveError();
    }
    records += 1;
    const headerSize = parseTarNumber(header.subarray(124, 136));
    const typeflag = header[156];
    const type = typeflag === 0 ? '\0' : String.fromCharCode(typeflag);
    const name = decodeTarField(header.subarray(0, 100));
    const prefix = decodeTarField(header.subarray(345, 500));
    const ustarPath = prefix ? `${prefix}/${name}` : name;
    rejectAppleDoublePath(ustarPath);
    const effectiveSize = headerSize;
    const bodyOffset = offset + TAR_BLOCK_SIZE;
    const paddedSize = Math.ceil(effectiveSize / TAR_BLOCK_SIZE) * TAR_BLOCK_SIZE;
    if (bodyOffset + paddedSize > tar.length) throw archiveError();
    const body = tar.subarray(bodyOffset, bodyOffset + effectiveSize);
    if (tar.subarray(bodyOffset + effectiveSize, bodyOffset + paddedSize).some(
      (byte) => byte !== 0,
    )) throw archiveError();
    offset = bodyOffset + paddedSize;

    if (['x', 'g', 'L', 'K'].includes(type)) throw archiveError();
    const memberPath = ustarPath;
    const headerLink = decodeTarField(header.subarray(157, 257));
    const memberLink = headerLink;

    let memberType;
    if (type === '\0' || type === '0') memberType = 'regular';
    else if (type === '5') memberType = 'directory';
    else throw archiveError();
    if (memberType === 'directory' && effectiveSize !== 0) throw archiveError();
    if (memberLink !== '') throw archiveError();
    const expectedMode = memberType === 'directory' || memberPath.endsWith('/Install.command')
      ? 0o755
      : 0o644;
    if (parseTarNumber(header.subarray(100, 108)) !== expectedMode
      || parseTarNumber(header.subarray(108, 116)) !== 0
      || parseTarNumber(header.subarray(116, 124)) !== 0
      || parseTarNumber(header.subarray(136, 148)) !== CANONICAL_MTIME_SECONDS
      || decodeTarField(header.subarray(265, 297)) !== 'root'
      || decodeTarField(header.subarray(297, 329)) !== 'root'
      || parseTarNumber(header.subarray(329, 337)) !== 0
      || parseTarNumber(header.subarray(337, 345)) !== 0) {
      throw archiveError();
    }

    const logicalPath = validateMemberPath(memberPath, memberType, profile);
    const collisionKey = logicalPath.normalize('NFC').toLocaleLowerCase('en-US');
    if (collisionKeys.has(collisionKey)) throw archiveError();
    collisionKeys.add(collisionKey);
    if (memberType === 'regular') {
      files.push(logicalPath);
      regularContents.set(logicalPath, body);
    } else {
      directories.push(logicalPath);
    }
  }
  if (!ended) throw archiveError();

  const expected = expectedArchiveMembers(profile);
  if (JSON.stringify(files.toSorted()) !== JSON.stringify(expected.files)
    || JSON.stringify(directories.toSorted()) !== JSON.stringify(expected.directories)) {
    throw archiveError('release_archive_members_mismatch');
  }
  const manifestPath = `${profile.name}/SHA256SUMS.txt`;
  const checksums = verifyChecksumManifest(
    regularContents.get(manifestPath), regularContents, profile,
  );
  return Object.freeze({
    regular: files.length,
    directories: directories.length,
    metadata: 0,
    appledouble: 0,
    symlinks: 0,
    special: 0,
    checksum_entries: checksums,
  });
}

async function normalizePackageTree(tempRoot, profile = releaseProfile()) {
  const expected = expectedArchiveMembers(profile);
  for (const member of expected.files) {
    const absolute = path.join(tempRoot, ...member.split('/'));
    await chmod(
      absolute,
      member.endsWith('/Install.command') ? 0o755 : 0o644,
    );
    await utimes(absolute, CANONICAL_MTIME, CANONICAL_MTIME);
  }
  for (const member of expected.directories.toReversed()) {
    const absolute = path.join(tempRoot, ...member.split('/'));
    await chmod(absolute, 0o755);
    await utimes(absolute, CANONICAL_MTIME, CANONICAL_MTIME);
  }
}

async function verifyExtractedTree(extracted, profile = releaseProfile()) {
  const files = [];
  const directories = [];
  async function visit(directory, relative = '') {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const nextRelative = relative ? `${relative}/${entry.name}` : entry.name;
      const absolute = path.join(directory, entry.name);
      const stat = await lstat(absolute);
      if (stat.isSymbolicLink()) throw archiveError();
      if (stat.isDirectory()) {
        directories.push(nextRelative);
        await visit(absolute, nextRelative);
      } else if (stat.isFile()) files.push(nextRelative);
      else throw archiveError();
    }
  }
  await visit(extracted);
  const expected = expectedArchiveMembers(profile);
  const expectedFiles = expected.files.map((member) => member.slice(profile.name.length + 1));
  const expectedDirectories = expected.directories
    .filter((member) => member !== profile.name)
    .map((member) => member.slice(profile.name.length + 1));
  if (JSON.stringify(files.toSorted()) !== JSON.stringify(expectedFiles.toSorted())
    || JSON.stringify(directories.toSorted()) !== JSON.stringify(expectedDirectories.toSorted())) {
    throw archiveError('release_archive_members_mismatch');
  }
}

async function verifyArchive(archive, tempRoot, {
  env,
  tarRunner,
}, profile = releaseProfile()) {
  const raw = await verifyReleaseArchiveRaw(archive, {}, profile.profile);

  const verifyRoot = path.join(tempRoot, 'verify');
  await mkdir(verifyRoot);
  await tarRunner('tar', ['-xzf', archive, '-C', verifyRoot], {
    env: releaseChildEnv(env),
  });
  const extracted = path.join(verifyRoot, profile.name);
  await verifyExtractedTree(extracted, profile);
  const checksumText = await readFile(path.join(extracted, 'SHA256SUMS.txt'), 'utf8');
  const checksumLines = checksumText.trimEnd().split('\n');
  if (checksumLines.length !== profile.files.length) {
    throw new ActionRequiredError(
      'release_checksum_invalid',
      'Extracted release checksum verification failed.',
    );
  }
  const seen = new Set();
  for (const line of checksumLines) {
    const match = /^([0-9a-f]{64})  (.+)$/u.exec(line);
    if (!match || seen.has(match[2]) || !profile.files.includes(match[2])
      || await hashFile(path.join(extracted, match[2])) !== match[1]) {
      throw new ActionRequiredError(
        'release_checksum_invalid',
        'Extracted release checksum verification failed.',
      );
    }
    seen.add(match[2]);
  }
  if (JSON.stringify([...seen].toSorted()) !== JSON.stringify(profile.files)) {
    throw new ActionRequiredError(
      'release_checksum_invalid',
      'Extracted release checksum verification failed.',
    );
  }
  return raw;
}

export async function buildRelease({
  repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'),
  output,
  env = process.env,
  tarRunner = execFileAsync,
  profile: profileName = 'full',
} = {}) {
  const profile = releaseProfile(profileName);
  const canonicalRepo = await realpath(repoRoot);
  if (typeof output !== 'string' || !path.isAbsolute(output)) {
    throw new ActionRequiredError(
      'release_output_required',
      'Release output must be an explicit absolute .tar.gz path.',
    );
  }
  if (!output.endsWith('.tar.gz') || isWithin(canonicalRepo, output)) {
    throw new ActionRequiredError(
      'release_output_unsafe',
      'Release output must be a .tar.gz path outside the source tree.',
    );
  }
  try {
    await lstat(output);
    throw new ActionRequiredError(
      'release_output_exists',
      'Release output already exists; refusing to overwrite it.',
    );
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
  const outputParent = path.dirname(output);
  const parentStat = await lstat(outputParent);
  if (!parentStat.isDirectory() || parentStat.isSymbolicLink()) {
    throw new ActionRequiredError(
      'release_output_parent_unsafe',
      'Release output parent must be an existing regular directory.',
    );
  }

  await validateSource(canonicalRepo);
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), 'erduo-release-'));
  let outputCreated = false;
  try {
    const packageRoot = path.join(tempRoot, profile.name);
    await mkdir(packageRoot);
    for (const relative of profile.files) {
      const destination = path.join(packageRoot, relative);
      await mkdir(path.dirname(destination), { recursive: true });
      await copyFile(path.join(canonicalRepo, relative), destination);
      await chmod(destination, relative === 'Install.command' ? 0o755 : 0o644);
    }
    await writeChecksums(packageRoot, profile.files);
    await normalizePackageTree(tempRoot, profile);
    const rawTar = path.join(tempRoot, `${profile.name}.tar`);
    await tarRunner('tar', [
      '--no-xattrs',
      '--format', 'ustar',
      '--uid', '0',
      '--gid', '0',
      '--uname', 'root',
      '--gname', 'root',
      '-cf', rawTar,
      '-C', tempRoot,
      profile.name,
    ], {
      env: releaseChildEnv(env),
    });
    const rawTarBytes = await readBoundedRegularFile(rawTar, MAX_UNCOMPRESSED_BYTES);
    const compressed = gzipSync(rawTarBytes, { level: 9 });
    compressed[9] = 255;
    verifyCanonicalGzipHeader(compressed);
    await writeFile(output, compressed, { flag: 'wx', mode: 0o644 });
    outputCreated = true;
    const raw = await verifyArchive(output, tempRoot, { env, tarRunner }, profile);
    return {
      status: 'packaged',
      profile: profile.profile,
      version: RELEASE_VERSION,
      files: profile.files.length + 1,
      archive: output,
      raw_archive: raw,
    };
  } catch (error) {
    if (outputCreated) await rm(output, { force: true }).catch(() => {});
    throw error;
  } finally {
    await rm(tempRoot, { recursive: true, force: true }).catch(() => {});
  }
}

async function main(argv) {
  let profile = 'full';
  let output = null;
  for (let index = 0; index < argv.length; index += 1) {
    if (argv[index] === '--profile') {
      profile = argv[index + 1];
      index += 1;
    } else if (argv[index] === '--output') {
      output = argv[index + 1];
      index += 1;
    } else {
      throw new ActionRequiredError('usage', 'Unknown release option.');
    }
  }
  if (!output) {
    throw new ActionRequiredError(
      'usage',
      'Usage: package-release.mjs [--profile full|standard] --output /absolute/external/path.tar.gz',
    );
  }
  const report = await buildRelease({ output, profile });
  process.stdout.write(`${JSON.stringify(report)}\n`);
}

const isMain = process.argv[1]
  && realpathSync(path.resolve(process.argv[1])) === realpathSync(fileURLToPath(import.meta.url));
if (isMain) {
  try {
    await main(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(`${JSON.stringify(publicError(error))}\n`);
    process.exitCode = error?.code === 'usage' ? 64 : 2;
  }
}
