"""The shell env file mirroring the web tool credentials out of ``config.json``.

``~/.raven/env`` exists for consumers that never read raven's config: the
user's own shell, and every ``cli`` / ``acp`` sub-agent, whose environment is a
capture of ``$SHELL -lic`` (see ``raven.agent.subagent.backends.env``) rather
than anything raven hands down. A ``kind: openai`` sub-agent is an HTTP call
with no subprocess, so no environment variable reaches it at all.

It is a *derived* artefact, never a second source of truth -- which only holds
if every writer of these keys refreshes it. There are three (the onboard
wizard, the web UI's tools page, and ``settings.set``), so the refresh lives
here rather than in any one of them; wiring it at a single call site is what
left a key rotated from the UI asserting its old value to every sub-agent.

It is deliberately not called from ``update_tools``' setters: those take a
``config_path`` for tests and library callers, and firing a write at
``Path.home()`` from them would put the developer's real credentials file in
the blast radius of any suite that patches only the config path.
"""

from __future__ import annotations

import shlex
from pathlib import Path
from typing import Optional

from loguru import logger

from raven.config.schema import WEB_VENDOR_ENV_VARS

_HEADER = (
    "# Generated by raven. Do not edit -- rewritten whenever the keys change.\n"
    "# Source of truth: config.json (tools.web.providers.<vendor>.apiKey; the\n"
    "# pre-vendor tools.web.search.apiKey and tools.web.jinaApiKey still count)\n"
)

#: Config keys whose write has to refresh the mirror, in the dotted spelling
#: ``settings.set`` addresses them by. Named once so a caller cannot guess.
MIRRORED_KEYS = (
    "tools.web.search.apiKey",
    "tools.web.jinaApiKey",
    *(f"tools.web.providers.{vendor}.apiKey" for vendor in WEB_VENDOR_ENV_VARS),
)


def _marker(var: str) -> str:
    """Name of the flag recording that raven, not the user, exported ``var``."""
    return f"RAVEN_MIRRORED_{var}"


def _stanza(var: str, value: str) -> str:
    """The lines for one credential: export it, or retire raven's own.

    Dropping the export is not enough to clear a key. A shell that sourced the
    previous mirror already holds the value, and every shell started from it
    inherits it, so re-sourcing a file that merely lacks the line leaves the
    cleared credential live -- and the web tools resolve it through their
    environment fallback.

    The unset is guarded on a marker rather than issued blindly, because the
    mirror may only retire what it set: someone who exports the same variable in
    their own rc and never configured one here must keep it. The marker is
    exported alongside the value, so it travels into child shells with it and is
    absent exactly when raven did not put the value there.

    Written as ``if``, not ``[ ... ] && ...``: a trailing ``&&`` whose test fails
    makes the whole file return non-zero, which a caller sourcing it would read
    as an error.
    """
    flag = _marker(var)
    if value:
        return f"export {var}={shlex.quote(value)}\nexport {flag}=1\n"
    return f'if [ -n "${{{flag}-}}" ]; then unset {var} {flag}; fi\n'


def write_env_file() -> Optional[Path]:
    """Rewrite ``~/.raven/env`` from config. Returns the path, or ``None``.

    ``None`` means there was nothing to say and no stale file to correct. An
    existing file is always rewritten: a key cleared in config has to be retired
    here too, or every shell that already sourced it keeps the credential alive.
    """
    from raven.config.paths import get_env_file, restrict_to_owner
    from raven.config.update_tools import get_web_provider_keys

    keys = get_web_provider_keys()
    path = get_env_file()
    if not keys and not path.exists():
        return None

    # One stanza per vendor, set or not: a vendor whose key was cleared needs
    # its retiring ``unset`` written, as the two original keys always had.
    body = _HEADER + "".join(_stanza(var, keys.get(vendor, "")) for vendor, var in WEB_VENDOR_ENV_VARS.items())

    path.parent.mkdir(parents=True, exist_ok=True)
    # Owner-only before the first secret byte: under the usual 0022 umask a
    # plain write lands 0644, and `touch` leaves the mode of a file that
    # already exists, which is what `restrict_to_owner` is here to tighten.
    path.touch(mode=0o600, exist_ok=True)
    restrict_to_owner(path)
    path.write_text(body, encoding="utf-8")
    return path


def refresh_env_file() -> None:
    """Best-effort ``write_env_file`` for callers whose own write already landed.

    The RPC surfaces reach here after the config file is on disk. A mirror that
    cannot be written (read-only home, full disk) does not undo that, and
    reporting the settings write as failed would be the wrong answer -- so the
    failure is logged and swallowed. The wizard calls ``write_env_file``
    directly instead, because there a failure is worth showing to the person
    who is sitting there configuring it.
    """
    try:
        write_env_file()
    except OSError as exc:
        logger.warning("Could not refresh the shell env mirror: {}", exc)


__all__ = ["MIRRORED_KEYS", "refresh_env_file", "write_env_file"]
